<?php  //[STAMP] e68adc3d73be9b773db3645674e28afb
namespace PyzTest\Yves\Checkout\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use PyzTest\Shared\Testify\Helper\Environment;
use SprykerTest\Shared\Config\Helper\ConfigInit;
use SprykerTest\Shared\Propel\Helper\ConnectionHelper;
use SprykerTest\Shared\Testify\Helper\DataCleanupHelper;

trait CheckoutBusinessTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Checks that array contains subset.
     *
     * @param array  $subset
     * @param array  $array
     * @param bool   $strict
     * @param string $message
     * @see \Codeception\Module::assertArraySubset()
     */
    public function assertArraySubset($subset, $array, $strict = null, $message = null) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('assertArraySubset', func_get_args()));
    }
}
