<ol class="cart-list">
  <?php foreach($items as $item) : ?>
    <li class="cart-item">
      <dl>
        <dt class="item-image"><img src="<?php echo $item->getProduct()->getArtTinyCrop(); ?>" alt="<?php echo $item->getName(); ?>">
        <dt class="name"><?php echo $item->getName(); ?>
        <dd class="author">John Doe
        <dd class="art-description"><?php echo $item->getProduct()->getProductName(); ?>
        <dd class="item-price"><?php echo price( $item->getGrossPrice()); ?>
        <dd class="item-quantity"><?php echo $item->getQuantity(); ?>
        <dd class="item-subtotal"><?php echo price( $item->getGrossPrice() * $item->getGrossPrice() ); ?>
      </dl>
   <?php endforeach; ?>
</ol>

<table class="cart-summary">
  <tbody>
    <tr>
      <th>subtotal:
      <td>123.00 €
    <tr>
      <th>shipping:
      <td>0.00 €
    <tr class="total">
      <th>total:
      <td>123.00 €
</table>
