<hgroup>
    <h1 class="heading"><?php echo t(Sao_Yves_Library_L::NEW_SHIPPING_ADDRESS_HEADING); ?></h1>

    <h2 class="sub-heading"><?php echo t(Sao_Yves_Library_L::REQUIRED_FIELDS_INFO); ?></h2>
</hgroup>
<ul class="form-list">
    <li class="row">
        <div class="column">
            <label for="first-name"><?php echo t(Sao_Yves_Library_L::FIRST_NAME); ?> *</label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[first_name]" id="first-name" required>
        </div>
    <li class="row">
        <div class="column">
            <label for="last-name"><?php echo t(Sao_Yves_Library_L::LAST_NAME); ?> *</label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[last_name]" id="last-name" required>
        </div>
    <li class="row">
        <div class="column">
            <label for="address"><?php echo t(Sao_Yves_Library_L::STREET_ADDRESS); ?> *</label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[address1]" id="address" required>
        </div>
    <li class="row">
        <div class="column">
            <label for="address-additional"><?php echo t(Sao_Yves_Library_L::STREET_ADDITIONAL); ?></label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[address2]" id="address-additional">
        </div>
    <li class="row">
        <div class="column">
            <label for="city"><?php echo t(Sao_Yves_Library_L::CITY); ?> *</label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[city]" id="city" required>
        </div>
    <li class="row">
        <div class="column">
            <label for="country"><?php echo t(Sao_Yves_Library_L::COUNTRY); ?> *</label>
        </div>
        <div class="column">
            <select class="input-field" name="Checkout_ShippingAddressForm[country]" id="country" required>
                <?php foreach ($countries as $isoCode => $name) : ?>
                <option value="<?php echo $isoCode; ?>"><?php echo $name; ?>
                <?php endforeach; ?>
            </select>
        </div>
    <li class="row">
        <div class="column">
            <label for="region"><?php echo t(Sao_Yves_Library_L::REGION); ?></label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[additional]" id="region">
        </div>
    <li class="row">
        <div class="column">
            <label for="postal"><?php echo t(Sao_Yves_Library_L::POSTAL); ?> *</label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[zip_code]" id="postal" required>
        </div>
    <li class="row">
        <div class="column">
            <label for="phone-number"><?php echo t(Sao_Yves_Library_L::PHONE_NUMBER); ?> *</label>
        </div>
        <div class="column">
            <input class="input-field" type="text" name="Checkout_ShippingAddressForm[cell_phone]" id="phone-number" required>
            <small><?php echo t(Sao_Yves_Library_L::PHONE_NUMBER_DISCLAIMER); ?></small>
        </div>
    <li class="row">
        <div class="column">
            <label for="use-it-for-billing">
                <input type="checkbox" name="shipping_as_billing" class="submit-button-routing-trigger" id="use-it-for-billing" checked>
                <?php echo t(Sao_Yves_Library_L::USE_SHIPPING_ADDRESS_FOR_BILLING); ?>
            </label>
        </div>
</ul>
