<h2 class="heading"><?php echo t( Sao_Yves_Library_L::PAYMENT_METHODS ); ?></h2>
<ul class="logos-list no-list horizontal-list">
  <li class="ir payment-visa" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_VISA ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_VISA ); ?>
  <li class="ir payment-mastercard" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_MASTERCARD ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_MASTERCARD); ?>
  <li class="ir payment-discover" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_DISCOVER ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_DISCOVER ); ?>
  <li class="ir payment-amex" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_AMEX ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_AMEX ); ?>
  <li class="ir payment-paypal" title="<?php echo t( Sao_Yves_Library_L::PAYPAL ); ?>"><?php echo t( Sao_Yves_Library_L::PAYPAL ); ?>
</ul>
