<?php
echo $this->crud;
echo
    ProjectA_Zed_Library_Ui_Button_Factory::getCta()->setLabel(__('save'))->setClick("document." . $this->form->getName() . ".submit()");
echo
    ProjectA_Zed_Library_Ui_Button_Factory::getCta()->setLabel(__('back'))->setClick("document.location = '/mail/sequence/element/id/" . $this->crud->getSequenceId() . "';");
?>

<div style="margin-top:40px;line-height: 1.5em;">
    Info:<br />
    If you connect a Codepool make sure to set the code`s validTo Interval and Format, otherwise creation of the mail template will fail.
    <br /><br />
    For the "code_valid_to_interval" you may use one of <a target="_blank" href="http://www.php.net/manual/en/datetime.formats.relative.php">PHP`s relative date format strings</a>.<br />
    <br />
    For the "code_valid_to_format" you may use one of <a target="_blank" href="http://php.net/manual/en/function.date.php">PHP`s date format strings</a>.<br />
    You should use 'l, F d' as default value.
</div>
