<?php
/** @var ProjectA_Zed_Sales_Persistence_PacSalesOrder $order */
$order = $this->order;
$shippingAddress = $order->getShippingAddress();
$billingAddress = $order->getBillingAddress();
$saoOrder = $order->getSaoOrder();

?>
<fieldset>
    <legend><? echo __('customer'); ?></legend>
    <strong><?php echo __('legacy information'); ?></strong>
    <ul>
        <?php if ($saoOrder) : ?>
            <li><?php echo __('userid'); ?>: <?php echo $saoOrder->getUserId(); ?></li>
        <?php endif; ?>

        <li><?php echo __('name'); ?>: <?php echo $order->getFirstName() . ' ' . $order->getLastName(); ?></li>

        <li><?php echo __('email'); ?>: <?php echo $order->getEmail(); ?></li>
    </ul>
    <table>
        <thead>
        <tr>
            <?php if (isset($this->editable) && $this->editable) : ?>
                <th>
                    <a href="/sales/order/edit-address/id/<?php echo $order->getIdSalesOrder(); ?>/type/shipping"><?php echo __('shipping address'); ?></a>
                </th>
                <th><a
                        href="/sales/order/edit-address/id/<?php echo $order->getIdSalesOrder(); ?>/type/billing"><?php echo __('billing address'); ?></a>
                </th>
            <?php else: ?>
                <th><?php echo __('shipping address'); ?></th>
                <th><?php echo __('billing address'); ?></th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <tr>

            <td>
                <?php echo $shippingAddress->getFirstName() . ' ' . $shippingAddress->getLastName(); ?><br>

                <?php if ($shippingAddress->getCompany()) : ?>
                    <?php echo $shippingAddress->getCompany() ?> <br/>
                <?php endif; ?>

                <?php echo $shippingAddress->getAddress1(); ?><br>
                <?php echo $shippingAddress->getAddress2(); ?><br>

                <?php echo $shippingAddress->getCity(); ?><br>
                <?php echo $shippingAddress->getZipCode(); ?><br>
                <?php if ($shippingAddress->getSaoAddress() && $shippingAddress->getSaoAddress()->getFkMiscRegion()) : ?>
                    <?php echo $shippingAddress->getSaoAddress()->getRegion()->getName() ?> <br/>
                <?php endif; ?>

                <?php echo $shippingAddress->getCountry()->getName(); ?><br>
                <?php echo $shippingAddress->getDescription(); ?><br>

                <?php echo __('cellphone') . ': ' . $shippingAddress->getCellPhone(); ?>
            </td>
            <td>
                <?php echo $billingAddress->getFirstName() . ' ' . $billingAddress->getLastName(); ?><br>

                <?php if ($billingAddress->getCompany()) : ?>
                    <?php echo $billingAddress->getCompany() ?> <br/>
                <?php endif; ?>

                <?php echo $billingAddress->getAddress1(); ?><br>
                <?php echo $billingAddress->getAddress2(); ?><br>

                <?php echo $billingAddress->getCity(); ?><br>
                <?php echo $billingAddress->getZipCode(); ?><br>
                <?php if ($billingAddress->getSaoAddress() && $billingAddress->getSaoAddress()->getFkMiscRegion()) : ?>
                    <?php echo $billingAddress->getSaoAddress()->getRegion()->getName() ?> <br/>
                <?php endif; ?>
                <?php echo $billingAddress->getCountry()->getName(); ?><br>
                <?php echo $billingAddress->getDescription(); ?>
            </td>
        </tr>
        </tbody>
    </table>
</fieldset>
