<?php
/** @var $note ProjectA_Zed_Sales_Persistence_PacSalesOrderNote */
?>

<fieldset>
    <legend><?php echo __('notes'); ?></legend>

    <table style="width: 100%">
        <thead>
        <tr>
            <th><?php echo __('date'); ?></th>
            <th><?php echo __('success'); ?></th>
            <th><?php echo __('message'); ?></th>
            <th><?php echo __('user'); ?></th>
            <th><?php echo __('from command'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php if (count($this->orderNotes) > 0) : ?>
            <?php foreach ($this->orderNotes as $note) : ?>
                <?php
                $commandStr = $note->getCommand();
                $expl = explode('_', $commandStr);
                $commandStr = end($expl);
                ?>
                <tr>
                    <td><?php echo Sao_Shared_Library_Date::dateSaoLong($note->getCreatedAt()) ?></td>

                    <?php if ($note->getSuccess()) : ?>
                        <td class="success"><?php echo __('yes'); ?></td>
                    <?php else: ?>
                        <td class="failure"><?php echo __('no'); ?></td>
                    <?endif; ?>

                    <td><?php echo $note->getMessage() ?></td>

                    <td><?php echo (null !== $note->getAclUser()) ? $note->getAclUser()->getFirstname() . ' ' . substr($note->getAclUser()->getLastname(), 0, 1) . '.' : 'System (cron)' ?></td>

                    <td><?php echo $commandStr ?></td>
                </tr>
            <?php endforeach; ?>

        <?php else: ?>
            <tr>
                <td colspan="5"><?php echo __('no notes available'); ?></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>

</fieldset>
