<?php
/* @var $item ProjectA_Zed_Sales_Persistence_PacSalesOrderItem */
?>

<fieldset>
    <legend><?php echo __('order status overview'); ?></legend>

    <table id="order-status-table">
        <thead>
        <tr>
            <th><?php echo __('id'); ?></th>
            <th><?php echo __('artist'); ?></th>
            <th><?php echo __('items'); ?></th>
            <th><?php echo __('quote'); ?></th>
            <th><?php echo __('process and status'); ?></th>

            <th><?php echo __('status history'); ?></th>
            <th><?php echo __('manual events'); ?></th>
        </tr>
        </thead>
        <?php foreach ($this->items as $c => $item) : ?>
            <?php $itemHistory = null; ?>
            <?php $process = $this->orderProcess ? $this->orderProcess : $item->getProcess(); ?>
            <?php if (isset($this->statusHistory[$item->getIdSalesOrderItem()])) : ?>
                <?php $itemHistory = $this->statusHistory[$item->getIdSalesOrderItem()]; ?>
            <?php endif; ?>
            <?php $quotes = $item->getQuotes(); ?>
            <?php $quoteStr = array(); ?>
            <?php foreach ($quotes as $quote) : ?>
                <?php $quoteStr[] = $quote->getProvider()->getName() . ' ' . $quote->getQuoteId(); ?>
            <?php endforeach; ?>

            <?php $product = $this->products[$item->getSku()]; ?>
            <?php $name = $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ARTIST_FIRST_NAME] . ' '; ?>
            <?php $name .= $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ARTIST_LAST_NAME]; ?>
            <?php $email = $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ARTIST_EMAIL]; ?>
            <?php $url = 'http://' . $this->apUserProfileUrl; ?>
            <?php $url .= $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ARTIST_USER_ID]; ?>
            
            <tr>
                <td><?php echo $item->getIdSalesOrderItem(); ?></td>
                <td>
                    <p class="bold">
                        <a href="<?php echo $url ?>" target="_blank"><?php echo $name ?></a>
                    </p>
                    <a href="mailto:<?php echo $email ?>"><?php echo $email ?></a>
                    <?php if ($product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_PRODUCT_SET] == 'marketplace') : ?>
                        <p>
                            <?php echo ($product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ARTIST_PHONE]) ? $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ARTIST_PHONE] . '<br>' : ''; ?>
                            <?php echo $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_ADDRESS1]; ?>
                            <br>
                            <?php echo ($product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_ADDRESS2]) ? $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_ADDRESS2] . '<br>' : ''; ?>
                            <?php echo $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_CITY]; ?>
                            ,<?php echo $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_ZIPCODE]; ?>
                            <br>
                            <?php echo ($product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_REGION]) ? $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_REGION] . '<br>' : ''; ?>
                            <?php echo ($product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_COUNTRY]) ? : $product[Sao_Shared_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ORIGIN_COUNTRY]; ?>
                        </p>
                    <?php endif; ?>
                </td>
                <td class="item-cell">
                    <?php echo $this->partial('statusoverview/iteminfotable.phtml', array('item' => $item, 'product' => $product)); ?>
                </td>
                <td><?php echo implode(', ', $quoteStr); ?></td>
                <td><p class="bold"><?php echo $process->getName(); ?></p>
                    <a target="_blank"
                       href="/sales/state-machine/render-item-status/id/<?php echo $item->getIdSalesOrderItem(); ?>"><?php echo __('show item status'); ?></a>
                    <?php if ($this->clarifyRefundStates->contains($item->getStatus())): ?>
                        <br />
                        <br />
                        <div>
                        <?php if (!$item->getSaoSalesOrderItem()->getMarkedForRefund()): ?>
                            <a href="/sales/order-item/mark-for-refund/id/<?php echo $item->getIdSalesOrderItem();     ?>/order-id/<?php echo $item->getOrder()->getIdSalesOrder(); ?>"
                               class="button">mark for refund</a>
                        <?php else: ?>
                            <a href="/sales/order-item/unmark-for-refund/id/<?php echo $item->getIdSalesOrderItem();     ?>/order-id/<?php echo $item->getOrder()->getIdSalesOrder(); ?>"
                               class="button">unmark for refund</a>
                        <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </td>
                <td class="history-cell">
                    <?php echo $this->partial('statusoverview/statushistorytable.phtml', array('itemHistory' => $itemHistory, 'currentStatus' => $item->getStatus()->getName())); ?>
                </td>
                <td>
                    <?php echo $this->partial('trigger/buttons.phtml', array('item' => $item, 'events' => $this->manuallyExecuteableEventsByItem[$item->getIdSalesOrderItem()], 'clarifyRefundStates' => $this->clarifyRefundStates)); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</fieldset>
