<?php
/**
 * @var Sao_Yves_Checkout_Component_Form_BillingAddress $billingAddressForm
 */
?>
<script id="checkout-step-billing-address-template" type="text/x-lodash-template">
<div class="row checkout-address-container">
  <section class="large-5 column">
    <hgroup>
      <h1 class="heading"><?php echo t( Sao_Yves_Library_L::NEW_BILLING_ADDRESS_HEADING ); ?></h1>
      <h2 class="sub-heading"><?php echo t( Sao_Yves_Library_L::REQUIRED_FIELDS_INFO ); ?></h2>
    </hgroup><?php

$form_array = [
  'initial' => [
    'action'  => '#step:payment'
  ],
  'review' => [
    'action'  => '#step:review'
  ]
];

?>
    <form action="#step:payment" id="billing-address-form" method="post" class="styled-form address-form billing" novalidate data-js-validate <?php echo Sao_Yves_Library_Form_Html::getJsonDataAttr( 'routing', $form_array ); ?>>
      <ul class="form-list">
        <li class="row">
          <div class="small-4 column">
            <label for="billing-first-name"><?php echo t( Sao_Yves_Library_L::FIRST_NAME ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="firstName" id="billing-first-name" required data-error-label="<?php echo t( Sao_Yves_Library_L::FIRST_NAME_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($billingAddressForm->first_name) ?> maxlength="100">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('first_name'), 'first-name') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="billing-first-name"><?php echo t( Sao_Yves_Library_L::LAST_NAME ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="lastName" id="billing-last-name" required data-error-label="<?php echo t( Sao_Yves_Library_L::LAST_NAME_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($billingAddressForm->last_name) ?> maxlength="100">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('last_name'), 'last-name') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="billing-address"><?php echo t( Sao_Yves_Library_L::STREET_ADDRESS ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="address" id="billing-address" required data-error-label="<?php echo t( Sao_Yves_Library_L::STREET_ADDRESS_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($billingAddressForm->address1) ?> maxlength="255" data-min-length="2" data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_ADDRESS1_MIN_LENGTH); ?>">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('address1'), 'address') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="billing-address-additional"><?php echo t( Sao_Yves_Library_L::STREET_ADDITIONAL ); ?></label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="addressAdditional" id="billing-address-additional" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($billingAddressForm->address2) ?>>
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('address2'), 'address-additional') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="billing-city"><?php echo t( Sao_Yves_Library_L::CITY ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="city" id="billing-city" required data-error-label="<?php echo t( Sao_Yves_Library_L::CITY_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($billingAddressForm->city) ?> maxlength="255" data-min-length="2" data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_CITY_MIN_LENGTH); ?>">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('city'), 'city') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="billing-country"><?php echo t( Sao_Yves_Library_L::COUNTRY ); ?>: *</label>
          </div>
          <div class="small-8 column">
              <select class="input-field" name="country" id="billing-country" required data-error-label="<?php echo t( Sao_Yves_Library_L::COUNTRY_ERROR ); ?>" >
                  <?php $iso2Attributes = $billingAddressForm->getElement('iso2_country')->getAttributes() ?>
                  <?php foreach ($countries as $isoCode => $name) : ?>
                  <option
                      value="<?php echo $isoCode; ?>" <?php echo Sao_Yves_Library_Form_Html::getSelectedIf($iso2Attributes['value'], $isoCode); ?>><?php echo $name; ?>
                      <?php endforeach; ?>
              </select>
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('country'), 'country') ?>
          </div>
        <li class="row" data-bound-to="billing-country" data-bound-to-value="*">
          <div class="small-4 column">
            <label for="billing-region"><?php echo t( Sao_Yves_Library_L::REGION ); ?></label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="region" id="billing-region" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($billingAddressForm->additional) ?> >
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('additional'), 'region') ?>
          </div>
        <?php foreach ( $regions as $iso => $regionsArray ): ?>
          <li class="row hidden" data-bound-to="billing-country" data-bound-to-value="<?php echo $iso; ?>">
            <div class="small-4 column">
            <?php // TODO: handle translation for the labels nicer... somnehow ?>
              <label for="billing-region-<?php echo $iso; ?>"><?php echo t( Sao_Yves_Library_L::REGION.'_'.$iso ); ?>: *</label>
            </div>
            <div class="small-8 column">
              <select class="input-field" name="region" id="billing-region-<?php echo $iso; ?>" required data-error-label="<?php echo t( Sao_Yves_Library_L::REGION_ERROR ); ?>" disabled>
                <option value="" selected>-----
                <?php foreach ( $regionsArray as $regionShort => $regionLong ): ?>
                  <option value="<?php echo $regionShort; ?>"><?php echo $regionLong; ?>
                <?php endforeach; ?>
              </select>
            </div>
        <?php endforeach; ?>

        <li class="row">
          <div class="small-4 column">
            <label for="billing-postal"><?php echo t( Sao_Yves_Library_L::POSTAL ); ?>:</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="postal" id="billing-postal" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($billingAddressForm->zip_code) ?> >
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($billingAddressForm->getErrors('zip_code'), 'postal') ?>
          </div>
        <li class="row form-action">
          <div class="large-offset-4 large-8 column">
            <input type="submit" value="<?php echo t( Sao_Yves_Library_L::BILL_THIS_ADDRESS ); ?>" class="submit-button">
          </div>
      </ul>
    </form>
  </section>
</div>
<div class="row text-left link-back-container">
  <?php

$link_back_array = [
  'initial' => [
    'label' => t( Sao_Yves_Library_L::BACK_TO_SHIPPING_ADDRESS ),
    'href'  => '#step:shipping-address'
  ],
  'review' => [
    'label' => t( Sao_Yves_Library_L::BACK_TO_ORDER_REVIEW ),
    'href'  => '#step:review'
  ]
];

?>
  <a href="#step:shipping-address" class="link-back" <?php echo Sao_Yves_Library_Form_Html::getJsonDataAttr( 'routing', $link_back_array ); ?>><?php echo t( Sao_Yves_Library_L::BACK_TO_SHIPPING_ADDRESS ); ?></a>
</div>
<aside class="row checkout-aside">
<aside class="row checkout-aside">
  <div class="large-4 column">
    <?php $this->renderPartial('checkout/index/partials/payment_methods', array()); ?>
  </div>
  <div class="large-4 column">
    <?php $this->renderPartial('checkout/index/partials/shipping_providers', array()); ?>
  </div>
  <div class="large-4 column">
    <?php $this->renderPartial('checkout/index/partials/secure_payment', array()); ?>
  </div>
</aside>
</aside>
</script>
