<?php
/**
 * @var Sao_Yves_Checkout_Component_Form_ShippingAddress            $shippingAddressForm
 * @var Sao_Yves_Checkout_Component_Form_AlternativeShippingAddress $alternativeShippingAddressForm
 */
?>
<script id="checkout-step-shipping-address-template" type="text/x-lodash-template">
<div class="row checkout-address-container">
  <section class="large-5 column">
    <hgroup>
      <h1 class="heading"><?php echo t( Sao_Yves_Library_L::NEW_SHIPPING_ADDRESS_HEADING ); ?></h1>
      <h2 class="sub-heading"><?php echo t( Sao_Yves_Library_L::REQUIRED_FIELDS_INFO ); ?></h2>
    </hgroup><?php

$form_array = [
  'initial' => [
    'action'  => '#step:billing-address'
  ],
  'review' => [
    'action'  => '#step:review'
  ]
];

?>
    <form action="#step:billing-address" id="shipping-address-form" method="post" class="styled-form address-form shipping" novalidate data-js-validate <?php echo Sao_Yves_Library_Form_Html::getJsonDataAttr( 'routing', $form_array ); ?>>
      <ul class="form-list">
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-first-name"><?php echo t( Sao_Yves_Library_L::LOGIN_FIRST_NAME ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="firstName" id="shipping-first-name" required data-error-label="<?php echo t( Sao_Yves_Library_L::FIRST_NAME_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->first_name) ?> maxlength="100">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('first_name'), 'first-name') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-first-name"><?php echo t( Sao_Yves_Library_L::LOGIN_LAST_NAME ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="lastName" id="shipping-last-name" required data-error-label="<?php echo t( Sao_Yves_Library_L::LAST_NAME_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->last_name) ?> maxlength="100">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('last_name'), 'last-name') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-address"><?php echo t( Sao_Yves_Library_L::STREET_ADDRESS ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="address" id="shipping-address" required data-error-label="<?php echo t( Sao_Yves_Library_L::STREET_ADDRESS_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->address1) ?> maxlength="255" data-min-length="2" data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_ADDRESS1_MIN_LENGTH); ?>">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('address1'), 'address') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-address-additional"><?php echo t( Sao_Yves_Library_L::STREET_ADDITIONAL ); ?></label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="addressAdditional" id="shipping-address-additional" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->address2) ?> >
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('address2'), 'address-additional') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-city"><?php echo t( Sao_Yves_Library_L::CITY ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="city" id="shipping-city" required data-error-label="<?php echo t( Sao_Yves_Library_L::CITY_ERROR ); ?>" data-required-for-manual <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->city) ?> maxlength="255" data-min-length="2" data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_CITY_MIN_LENGTH); ?>">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('city'), 'city') ?>
         </div>
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-country"><?php echo t( Sao_Yves_Library_L::COUNTRY ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <select class="input-field" name="country" id="shipping-country" data-error-label="<?php echo t( Sao_Yves_Library_L::COUNTRY_ERROR ); ?>" required data-required-for-manual>
                <?php $iso2Attributes = $shippingAddressForm->getElement('iso2_country')->getAttributes()?>
                <?php foreach($countries as $isoCode => $name) : ?>
                  <option value="<?php echo $isoCode; ?>" <?php echo Sao_Yves_Library_Form_Html::getSelectedIf($iso2Attributes['value'], $isoCode); ?>><?php echo $name; ?>
              <?php endforeach; ?>
            </select>
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('country'), 'country') ?>
          </div>
        <li class="row" data-bound-to="shipping-country" data-bound-to-value="*">
          <div class="small-4 column">
            <label for="shipping-region"><?php echo t( Sao_Yves_Library_L::REGION ); ?></label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="region" id="shipping-region" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->region) ?> >
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('region'), 'region') ?>

          </div>
        <?php foreach ( $regions as $iso => $regionsArray ): ?>
          <li class="row hidden" data-bound-to="shipping-country" data-bound-to-value="<?php echo $iso; ?>">
            <div class="small-4 column">
            <?php // TODO: handle translation for the labels nicer... somnehow ?>
              <label for="shipping-region-<?php echo $iso; ?>"><?php echo t( Sao_Yves_Library_L::REGION.'_'.$iso ); ?>: *</label>
            </div>
            <div class="small-8 column">
              <select class="input-field" name="region" id="shipping-region-<?php echo $iso; ?>" required data-error-label="<?php echo t( Sao_Yves_Library_L::REGION_ERROR ); ?>" data-required-for-manual disabled>
                <option value="" selected>-----
                <?php foreach ( $regionsArray as $regionShort => $regionLong ): ?>
                  <option value="<?php echo $regionShort; ?>"><?php echo $regionLong; ?>
                <?php endforeach; ?>
              </select>
            </div>
        <?php endforeach; ?>
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-postal"><?php echo t( Sao_Yves_Library_L::POSTAL ); ?>:</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="postal" id="shipping-postal" data-required-for-manual <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->zip_code) ?> >
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('zip_code'), 'postal') ?>
          </div>
        <li class="row">
          <div class="small-4 column">
            <label for="shipping-phone-number"><?php echo t( Sao_Yves_Library_L::PHONE_NUMBER ); ?>: *</label>
          </div>
          <div class="small-8 column">
            <input class="input-field" type="text" name="phoneNumber" id="shipping-phone-number" data-min-length="3" maxlength="20" required data-error-label="<?php echo t( Sao_Yves_Library_L::CELL_PHONE_ERROR ); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($shippingAddressForm->cell_phone) ?> data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_PHONE_LENGTH); ?>">
            <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($shippingAddressForm->getErrors('cell_phone'), 'phone-number') ?>
            <small><?php echo t( Sao_Yves_Library_L::PHONE_NUMBER_DISCLAIMER ); ?></small>
          </div>
        <li class="row">
          <div class="large-offset-4 large-8 column">
            <label for="use-it-for-billing">
              <input type="checkbox" name="shippingAsBilling" class="submit-button-routing-trigger" id="use-it-for-billing" <?php echo Sao_Yves_Library_Form_Html::getCheckedIf($alternativeShippingAddressForm->alternative_shipping_address, true), Sao_Yves_Library_Form_Html::getCheckedIf($alternativeShippingAddressForm->alternative_shipping_address, null) ?> >
              <?php echo t( Sao_Yves_Library_L::USE_SHIPPING_ADDRESS_FOR_BILLING ); ?>
                <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($alternativeShippingAddressForm->getErrors('alternative_shipping_address'), 'use-it-for-billing') ?>
            </label>
          </div>
        <li class="row form-action">
          <div class="large-offset-4 large-8 column">
            <?php

$submit_button_array = [
  'false' => t( Sao_Yves_Library_L::PROCEED_TO_BILLING_ADDRESS ),
  'true'  => t( Sao_Yves_Library_L::PROCEED_TO_PAYMENT_METHOD )
  // TODO: review?
  // TODO: logic-wise change
];

?>
            <button type="submit" class="submit-button" <?php //echo Yp_Form_Html::getJsonDataAttr( 'labels', $submit_button_array ); ?>><?php echo t( Sao_Yves_Library_L::PROCEED_TO_PAYMENT_METHOD ); ?></button>
          </div>
      </ul>
    </form>
  </section>
</div>
<div class="row text-left link-back-container">
  <?php

$link_back_array = [
  'initial' => [
    'label' => t( Sao_Yves_Library_L::BACK_TO_CART ),
    'href'  => '/cart'
  ],
  'review' => [
    'label' => t( Sao_Yves_Library_L::BACK_TO_ORDER_REVIEW ),
    'href'  => '#step:review'
  ]
];

?>
  <a href="/cart" class="link-back" <?php echo Sao_Yves_Library_Form_Html::getJsonDataAttr( 'routing', $link_back_array ); ?>><?php echo t( Sao_Yves_Library_L::BACK_TO_CART ); ?></a>
</div>
<aside class="row checkout-aside">
  <div class="large-4 column">
    <?php $this->renderPartial('checkout/index/partials/payment_methods', array()); ?>
  </div>
  <div class="large-4 column">
    <?php $this->renderPartial('checkout/index/partials/shipping_providers', array()); ?>
  </div>
  <div class="large-4 column">
    <?php $this->renderPartial('checkout/index/partials/secure_payment', array()); ?>
  </div>
</aside>
</script>
