<?php
echo $this->headLink()
    ->prependStylesheet('/new/styles/vendor/projecta.css')
    ->prependStylesheet('/new/styles/vendor/kendoui/kendo.default.min.css')
    ->prependStylesheet('/new/styles/vendor/kendoui/kendo.common.min.css')
    ->prependStylesheet('/new/styles/zed.css')
    ->prependStylesheet('/new/styles/vendor/bootstrap.min.css');

echo $this->headScript()
    ->prependFile('/new/scripts/zed.js')
    ->prependFile('/new/scripts/vendor/bootstrap.min.js')
    ->prependFile('/new/scripts/vendor/kendoui/kendo.web.min.js')
    ->prependFile('/new/scripts/vendor/kendoui/jquery.min.js');

