<?php
/** @var $this Sao_Yves_Transactionstatus_Module_Controller_Index */
?>
<?php $this->renderPartial('layouts/partials/head', array()); ?>
<body class="page-cart">
  <div class="page-wrap">
    <?php echo Sao_Yves_Legacy_Component_Model_Html_Header::render() ?>
    <main id="main" class="page-main cart" role="main">
        <?php echo $content; ?>
    </main>
  </div>
<?php $this->renderPartial('layouts/partials/footer', array()); ?>
