#!/bin/bash

set -o pipefail

SETUP='spryker'
DATABASE_NAME='DE_development_zed'
DATABASE_USER='development'
DATABASE_PASSWORD='mate20mg'
VERBOSITY='-v'
CONSOLE=vendor/bin/console
PHANTOMJS_CDNURL='https://github.com/Medium/phantomjs/'
ESSTORES=( de_search )

. deploy/setup/functions.sh

warningText "This script should be used only in development and NEVER IN PRODUCTION"

if [ $# -eq 0 ]; then
    displayHelp
    exit 0
fi

for arg in "$@"
do
    case $arg in
        "-iy" )
            errorText "This command is deprecated. Please use --install-yves or -yves instead"
            installYves
            ;;
        "-iz" )
            errorText "This command is deprecated. Please use --install-zed or -zed instead"
            installZed
            ;;
        "--install-demo-shop" | "-i" )
           installDemoshop
           ;;
        "--install-yves" | "-yves" )
           installYves
           ;;
        "--install-zed" | "-zed" )
           installZed
           ;;
        "--reset" | "-r" )
           resetDevelopmentState
           ;;
        "--dump-db" | "-ddb" )
           dumpDevelopmentDatabase
           ;;
        "--restore-db" | "-rdb" )
           restoreDevelopmentDatabase
           ;;
        "--help" | "-h" )
           displayHelp
           ;;
        "--clean" | "-c" )
           optimizeRepo
           ;;
        *)
            displayHeader
            echo ""
            echo "Unrecognized option: $@. Use -h to display help."
            exit 1
        ;;
   esac
done

exit 0
