#!/bin/bash

set -o pipefail

. deploy/setup/util/print.sh
. deploy/setup/params.sh

if [[ -f deploy/setup/params_local.sh ]] ; then
    . deploy/setup/params_local.sh
fi

. deploy/setup/functions.sh
. deploy/setup/frontend/params.sh

if [[ -f deploy/setup/frontend/params_local.sh ]] ; then
    . deploy/setup/frontend/params_local.sh
fi

. deploy/setup/frontend/functions.sh

export APPLICATION_ENV='development'

warningText "This script should be used only in development and NEVER IN PRODUCTION"

if [ $# -eq 0 ]; then
    displayHelp
    exit 0
fi

for arg in "$@"
do
    case $arg in
        "-iy" )
            errorText "This command is deprecated. Please use --install-yves or -yves instead"
            installYves
            ;;
        "-iz" )
            errorText "This command is deprecated. Please use --install-zed or -zed instead"
            installZed
            ;;
        "--install-demo-shop" | "-i" | "-inc")
           installDemoshop $arg
           ;;
        "--install-yves" | "-yves" )
           installYves
           ;;
        "--install-zed" | "-zed" )
           installZed
           ;;
        "--reset" | "-r" )
           resetDevelopmentState
           ;;
        "--dump-db" | "-ddb" )
           dumpDevelopmentDatabase
           ;;
        "--restore-db" | "-rdb" )
           restoreDevelopmentDatabase
           ;;
        "--help" | "-h" )
           displayHelp
           ;;
        "--clean" | "-c" )
           optimizeRepo
           ;;
        "--test-env" | "-t" )
           ./setup_test -b
           ;;

        *)
            displayHeader
            echo ""
            echo "Unrecognized option: $@. Use -h to display help."
            exit 1
        ;;
   esac
done

exit 0
