<?php



/* @var $product ProjectA_Zed_Catalog_Component_Interface_Product */
$product = $this->product;

/* @var $productEntity ProjectA_Zed_Catalog_Persistence_PacCatalogProduct */
$productEntity = $this->productEntity;


echo '<a href="/lumberjack#search%20&quot;'.$productEntity->getSku().'&quot;">Search in Lumberjack</a>';

echo '<hr />';

echo '<h1>Entity</h1><table border="1">';
echoRows($productEntity->toArray());
echo '</table>';

echo '<hr />';

echo '<h1>Stocks</h1><b style="color: #498816">Availability: '.$this->stock.'</b><br /><br /><table border="1">';
$stockProducts = $productEntity->getStockProducts();
foreach ($stockProducts as $stockProduct) {
    echoRows($stockProduct->toArray());
}
echo '</table>';



echo '<hr />';

echo '<h1>Prices</h1><table border="1">';
$priceProducts = $productEntity->getPriceProducts();
foreach ($priceProducts as $priceProduct) {
    echoRows($priceProduct->toArray());
}
echo '</table>';

echo '<hr />';

echo '<h1>Product</h1><table border="1">';
echoRows($product->toArray());
echo '</table>';

echo '<hr />';

echo '<h1>Orders</h1><table border="1">';
$orders = $this->orders;
foreach ($orders as $order) {
    /* @var ProjectA_Zed_Sales_Persistence_PacSalesOrder $order */
    echo '<tr>';
    echo '<td><b>ID</b></td><td><a href="/sales/order-details/index/id/'.$order->getIdSalesOrder().'">' . $order->getIdSalesOrder() . '</a></td>';
    echo '</tr>';
}
echo '</table>';


function echoRows($array)
{
    foreach ($array as $k => $v) {
        echo '<tr>';
        if (!is_scalar($v)) {
            $v = var_export($v, true);
        }
        echo '<td><b>' . $k . '</b></td><td>' . $v . '</td>';
        echo '</tr>';
    }
}

