<style type="text/css">
    #productDescription {
        width: 100%;
        clear: both;
        float: left;
        margin: 0 0 24px;
    }

    #headline {
        clear: both;
        float: left;
        margin: 5px 0;

        -moz-border-bottom-colors: none;
        -moz-border-image: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -moz-border-top-colors: none;
        border-color: #D1D1D1 #D1D1D1 -moz-use-text-color -moz-use-text-color;
        border-style: solid solid none none;
        border-width: 1px 1px medium medium;
        box-shadow: 0 0 7px #DDDDDD;
        display: table;
    }
    #headline h1 {
        margin: 10px;
    }
    #headline div {
        float: left;
        border-bottom: 1px solid #D1D1D1;
        border-left: 1px solid #D1D1D1;
        box-shadow: 1px 1px 6px rgba(0, 0, 0, 0.05) inset;
        display: table-cell;
        padding: 8px 12px;
        background: none repeat scroll 0 0 #EFEFEF;
    }
    .dates {
        float: right;
    }
    .warning {
        font-size: 12px;
        clear: both;
        float: left;
    }

</style>

<div class="dates">
    <p>Created: <?php echo $this->description['created_at']; ?></p>
    <p>Last updated: <?php echo $this->description['updated_at']; ?></p>
</div>
<div id="productDescription">
    <?php echo $this->form; ?>
</div>