<?php

namespace Generated\Zed\Ide;

/**
 * @method \Generated\Zed\Ide\Acl acl()
 * @method \Generated\Zed\Ide\Application application()
 * @method \Generated\Zed\Ide\Auth auth()
 * @method \Generated\Zed\Ide\Availability availability()
 * @method \Generated\Zed\Ide\AvailabilityCartConnector availabilityCartConnector()
 * @method \Generated\Zed\Ide\AvailabilityCheckoutConnector availabilityCheckoutConnector()
 * @method \Generated\Zed\Ide\Calculation calculation()
 * @method \Generated\Zed\Ide\Cart cart()
 * @method \Generated\Zed\Ide\Catalog catalog()
 * @method \Generated\Zed\Ide\Category category()
 * @method \Generated\Zed\Ide\CategoryExporter categoryExporter()
 * @method \Generated\Zed\Ide\CategoryTree categoryTree()
 * @method \Generated\Zed\Ide\Checkout checkout()
 * @method \Generated\Zed\Ide\Cms cms()
 * @method \Generated\Zed\Ide\Console console()
 * @method \Generated\Zed\Ide\Customer customer()
 * @method \Generated\Zed\Ide\Customer2 customer2()
 * @method \Generated\Zed\Ide\DbDump dbDump()
 * @method \Generated\Zed\Ide\DemoPayment demoPayment()
 * @method \Generated\Zed\Ide\Document document()
 * @method \Generated\Zed\Ide\Feed feed()
 * @method \Generated\Zed\Ide\FrontendExporter frontendExporter()
 * @method \Generated\Zed\Ide\Glossary glossary()
 * @method \Generated\Zed\Ide\GlossaryExporter glossaryExporter()
 * @method \Generated\Zed\Ide\Ide ide()
 * @method \Generated\Zed\Ide\Installer installer()
 * @method \Generated\Zed\Ide\Invoice invoice()
 * @method \Generated\Zed\Ide\Kendo kendo()
 * @method \Generated\Zed\Ide\Kernel kernel()
 * @method \Generated\Zed\Ide\Library library()
 * @method \Generated\Zed\Ide\Locale locale()
 * @method \Generated\Zed\Ide\Lumberjack lumberjack()
 * @method \Generated\Zed\Ide\Mail mail()
 * @method \Generated\Zed\Ide\Misc misc()
 * @method \Generated\Zed\Ide\Newsletter newsletter()
 * @method \Generated\Zed\Ide\Oms oms()
 * @method \Generated\Zed\Ide\Payment payment()
 * @method \Generated\Zed\Ide\PaymentControl paymentControl()
 * @method \Generated\Zed\Ide\Payone payone()
 * @method \Generated\Zed\Ide\Price price()
 * @method \Generated\Zed\Ide\Product product()
 * @method \Generated\Zed\Ide\ProductCategory productCategory()
 * @method \Generated\Zed\Ide\ProductCategorySearch productCategorySearch()
 * @method \Generated\Zed\Ide\ProductExporter productExporter()
 * @method \Generated\Zed\Ide\ProductFrontendExporterConnector productFrontendExporterConnector()
 * @method \Generated\Zed\Ide\ProductImage productImage()
 * @method \Generated\Zed\Ide\ProductSearch productSearch()
 * @method \Generated\Zed\Ide\Propel propel()
 * @method \Generated\Zed\Ide\PropelGen propelGen()
 * @method \Generated\Zed\Ide\Sales sales()
 * @method \Generated\Zed\Ide\Salesrule salesrule()
 * @method \Generated\Zed\Ide\Setup setup()
 * @method \Generated\Zed\Ide\Stock stock()
 * @method \Generated\Zed\Ide\StockSalesConnector stockSalesConnector()
 * @method \Generated\Zed\Ide\System system()
 * @method \Generated\Zed\Ide\Touch touch()
 * @method \Generated\Zed\Ide\Yves yves()
 * @method \Generated\Zed\Ide\YvesExport yvesExport()
 */
interface AutoCompletion
{}

