<h1><?php echo __('All'); ?></h1>
<br/>

<?php /* @var $customer ProjectA_Zed_Customer_Persistence_PacCustomer */
$customer = $this->customer; ?>

<div style="float:left;padding:5px;border-top:1px dotted #d3d3d3;border-left:1px dotted #d3d3d3;">
<?php echo $customer->getFirstName(); ?> <?php echo $customer->getLastName(); ?><br/>
<?php echo $customer->getEmail(); ?><br/>
<?php echo $customer->getGender(); ?><br/>
<?php echo $customer->getGender(); ?><br/>

</div>

<div class="clear"></div><br />
<a href="<?php echo $this->url(array('module' => 'customer', 'controller' => 'index', 'action' => 'save', 'id' => $this->customer->getIdCustomer()), null, true); ?>"><?php echo __('edit'); ?></a>
<br/><br/>
<hr/>
<br/>

<?php echo $this->grid; ?>
<a href="<?php echo $this->url(array('action' => 'save')); ?>"><?php echo __('New Address'); ?></a>