<?php
/*
$paymentMethods = array(
    '' => 'All'
);
$paymentMethods = array_merge($paymentMethods, SaoShafailure_PaymentMethods::getPaymentMethods());
?>

<div style="float: right">

    <?php
    foreach ($paymentMethods as $paymentMethod => $name) {
        echo '<a href="<?php echo Pal_Url::url(array('process' => $paymentMethod)) ?>"><?php echo $name ?></a> | ';
    }
    ?>

</div>

<?php */
if ($this->salesOrderAmount[ProjectA_Zed_System_Component_Model_Monitor_SalesOrderAmount::ORDERS_LAST_HOUR] < 15) {
    $lastHourColor = 'failure';
} else {
    $lastHourColor = 'success';
}

if ($this->salesOrderAmount[ProjectA_Zed_System_Component_Model_Monitor_SalesOrderAmount::ORDERS_CURRENT_HOUR] < 15) {
    $currentHourColor = 'failure';
} else {
    $currentHourColor = 'success';
}
if ($this->salesOrderAmount[ProjectA_Zed_System_Component_Model_Monitor_SalesOrderAmount::ORDERS_TODAY] < 100) {
    $dayColor = 'failure';
} else {
    $dayColor = 'success';
}

?>


<p class="paragraph">
    <a class="button<?php echo ($this->selectedButton == 1) ? ' off' : '' ?>"
       href="<?php echo ProjectA_Zed_Library_Url::url(array('show_test' => '1')) ?>">show test orders</a>
    <a class="button<?php echo ($this->selectedButton == 0) ? ' off' : '' ?>"
       href="<?php echo ProjectA_Zed_Library_Url::url(array('show_test' => '0')) ?>">show real orders</a>
    |
    <b class="<?php echo $lastHourColor ?>"><?php echo $this->salesOrderAmount[ProjectA_Zed_System_Component_Model_Monitor_SalesOrderAmount::ORDERS_LAST_HOUR] ?></b>
    orders last hour -
    <b class="<?php echo $currentHourColor ?>"><?php echo $this->salesOrderAmount[ProjectA_Zed_System_Component_Model_Monitor_SalesOrderAmount::ORDERS_CURRENT_HOUR] ?></b>
    orders current hour -
    <b class="<?php echo $dayColor ?>"><?php echo $this->salesOrderAmount[ProjectA_Zed_System_Component_Model_Monitor_SalesOrderAmount::ORDERS_TODAY] ?></b>
    orders today
</p>

<?php echo $this->grid; ?>
