<?php
$doubleClick_Aggregator = Sao_Yves_Tracking_Component_Model_DoubleClick_Aggregator::getInstance();
$pageType = $doubleClick_Aggregator->getParameter(Sao_Yves_Tracking_Component_Model_DoubleClick_Constants::DC_PAGE_TYPE);
?>

<script>var _gaq = _gaq || [];
_gaq.push(['_require','inpage_linkid','//www.google-analytics.com/plugins/ga/inpage_linkid.js']);
_gaq.push(['_setAccount','<?php echo $account; ?>']);
_gaq.push(['_setDomainName','.saatchionline.com']);
_gaq.push(['_setCustomVar',3,'pageType','<?php echo $pageType; ?>',3]);
_gaq.push(['_setCustomVar',1,'userType','collector']);
_gaq.push(['_trackPageview']);
<?php if($doubleClick_Aggregator->isSuccessPage()):

  $transParams = $doubleClick_Aggregator->getParameter(
    Sao_Yves_Tracking_Component_Model_DoubleClick_Constants::DC_ADD_TRANS
  );
    if (!empty($transParams)): // only log if we are not in manual checkout
      ?>
_gaq.push(['_addTrans', <?php echo $doubleClick_Aggregator->arrayValuesToString($transParams); ?>]);
      <?php foreach ($doubleClick_Aggregator->getOrderItems() as $item): ?>
_gaq.push(['_addItem', <?php echo $doubleClick_Aggregator->arrayValuesToString($item); ?>]);
      <?php endforeach; ?>
_gaq.push(['_trackTrans']);
    <?php endif;
endif; ?>
(function(){var ga = document.createElement('script');ga.src = '//stats.g.doubleclick.net/dc.js';
var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga, s);})();</script>
