<div style="float: right"><a href="/sales/order-details/index/id/<?php echo $this->order->getIdSalesOrder()?>">go to order</a></div>
<h2>OrderItem-State-Machine Activity Log</h2>
<?php if(count($this->activityLog) > 0){?>
<table style="font-size: 10px; width: 100%">
    <thead>
    <th>Time</th>
    <th>ID OrderItem</th>
    <th>SKU OrderItem</th>
    <th>Event</th>
    <th>Locked?</th>
    <th>Error?</th>
    <th>Source-State</th>
    <th>Target-State</th>
    <th>Executed Commands</th>
    <th>Condition which was true</th>
    <!--<th>Parameters</th>-->
    <th>Triggered in</th>
    <th>User</th>
    <th>Host</th>

    </thead>
    <?php foreach($this->activityLog as $log){ /* @var $log ProjectA_Zed_Sales_Persistence_PacSalesOrderItemTransitionLog */?>
    <tr>
        <td><?php echo $log->getCreatedAt() ?></td>
        <td><?php echo $log->getFkSalesOrderItem() ?></td>
        <td><?php echo $log->getOrderItem()->getSku() ?></td>
        <td><?php echo $log->getEvent() ?></td>
        <td><?php echo $log->getLocked()?'yes':'no' ?></td>
        <td><?php echo $log->getError()?'yes':'no' ?>
            <?php
            if($log->getError())
            {
                echo '<br />'.$log->getErrorMessage();
            }
            ?>

        </td>
        <td><?php echo $log->getSourceState() ?></td>
        <td><?php echo $log->getTargetState() ?></td>
        <td>
            <?php if(count($log->getCommands()) > 0){ ?>
            <?php echo '<ul><li>'.implode('</li><li>', $log->getCommands()).'</li></ul>' ?>
            <?php } ?>
        </td>
        <td>
            <?php if(count($log->getConditions()) > 0){ ?>
            <?php echo '<ul><li>'.implode('</li><li>', $log->getConditions()).'</li></ul>' ?>
            <?php } ?>
        </td>
        <!--<td><?php echo '<ul><li>'.implode('</li><li>', $log->getParams()).'</li></ul>' ?></td>-->
        <td><?php echo $log->getModule().'|'.$log->getController().'|'.$log->getAction() ?></td>
        <td><?php
            $aclUser = $log->getAclUser();
            if (isset($aclUser)) {
                echo $aclUser->getUsername();
            } else {
                echo 'no';
            }
            ?>

        </td>
        <td><?php echo $log->getHostname() ?></td>
    </tr>


    <?php } ?>
</table>


<?php } ?>