<?php /* @var Sao\Yves\Library\Templating\Scope\TemplateScope $this */ ?>
<?php /* @var ProjectA_Shared_Sales_Transfer_Order_Item $cartItem */ ?>
<pre>
<?php foreach($this->getArray('cartItems') as $cartItem): ?>

    SKU: <?= $cartItem->getSku(); ?>
    Name: <?= $cartItem->getName(); ?>
    Quantity: <?= $cartItem->getQuantity(); ?>
    Price: <?= $cartItem->getGrossPrice(); ?>

<?php endforeach; ?>
</pre>
