<?php /* @var Sao\Yves\Library\Templating\Scope\TemplateScope $this */ ?>
<?php /* @var ProjectA_Shared_Sales_Transfer_Order_Item $cartItem */ ?>
<pre>
    Cart-Hash: <?= $this->getString('cartHash'); ?>


<?php foreach($this->getArray('cartItems') as $cartItem): ?>

    SKU: <?= $cartItem->getSku(); ?>

    UID: <?= $cartItem->getUniqueIdentifier(); ?>

    Name: <?= $cartItem->getName(); ?>

    Quantity: <?= $cartItem->getQuantity(); ?>

    Price: <?= $this->price()->format($cartItem->getGrossPrice()); ?>



<?php endforeach; ?>
</pre>
