<?php
/** @var $comment ProjectA_Zed_Sales_Persistence_PacSalesOrderComment */
?>

<fieldset>
    <legend><?php echo __('comments') ?></legend>
    <table id="comments-table">

        <thead>
        <tr>
            <th><?php echo __('created'); ?></th>
            <th><?php echo __('user'); ?></th>
            <th><?php echo __('comment'); ?></th>
        </tr>
        </thead>
        <tbody>

        <?php if (count($this->comments) == 0) : ?>
            <tr>
                <td colspan="3"><?php echo __('no comments available'); ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->comments as $comment) : ?>
                <tr>
                    <td><?php echo Sao_Shared_Library_Date::dateSaoLong($comment->getCreatedAt()); ?></td>
                    <td><?php echo $comment->getUsername() ?></td>
                    <td><?php echo nl2br($comment->getMessage()) ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <p><a class="button"
          href="/sales/comments/add/sales_order_id/<?php echo $this->order->getIdSalesOrder() ?>"><?php echo __('add a new comment') ?></a>
    </p>
</fieldset>
