<fieldset>
    <legend><?php echo __('payment'); ?></legend>
    <?php echo $this->partial('payment.phtml', array('payment' => $this->payment, 'account' => $this->account, 'transactions' => $this->transactions, 'orderId' => $this->order->getPrimaryKey())); ?>

    <?php if ($this->order->getPayment()) : ?>
        <?php $rawresponse = json_decode($this->order->getPayment()->getPaymentTransactions()->getLast()->getRawResponse()); ?>
        <?php if (isset($rawresponse->card) && isset($rawresponse->card->type)): ?>
            <br>
            <h2><?php echo __('card type') ?></h2>
            <?php echo $rawresponse->card->type ?>
        <?php endif; ?>
    <?php endif; ?>
</fieldset>
