<?php

/** @var $quote Sao_Zed_Fulfillment_Persistence_FulfillmentQuote */
/** @var $tracking Sao_Zed_Fulfillment_Persistence_FulfillmentShippingTracking */
/** @var $status Sao_Zed_Fulfillment_Persistence_FulfillmentShippingTrackingStatusHistory */

$trackings = $this->quote->getTrackings();
?>

<?php if ($trackings->count() != 0) : ?>
    <table>
        <thead>
        <tr>
            <th><?php echo __('Agent') ?></th>
            <th><?php echo __('Tracking #') ?></th>
            <th><?php echo __('Tracking URL') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($trackings as $tracking) : ?>
            <tr>
                <td><?php echo $tracking->getShippingAgent()->getName(); ?></td>
                <td><?php echo $tracking->getTrackingNumber(); ?></td>
                <td>
                    <a href="<?php echo $tracking->getShippingAgent()->getTrackingUrl() . $tracking->getTrackingNumber(); ?>">
                        <?php echo __('link') ?></a></td>
            </tr>

            <?php if ($tracking->getTrackingStatuses()->count() == 0) {
                continue;
            } ?>

            <tr>
                <td colspan="3">
                    <strong><?php echo __('history') ?>:</strong><br/>
                    <ul>
                        <?php foreach ($tracking->getTrackingStatuses() as $status) : ?>
                            <li><?php echo $status->getCode() . ' ' . $status->getDescription() . ' (' . $status->getUpdatedAt(); ?>
                                )
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    &nbsp;
<?php endif; ?>