<fieldset>
    <legend><?php echo __('manual state machine triggers for all order items') ?></legend>
    <?php if ($this->manuallyExecuteableEventsByOrder) : ?>
        <?php foreach ($this->manuallyExecuteableEventsByOrder as $event) : ?>
            <a href="/sales/order-details/fire-event-order/id_sales_order/<?php echo $this->order->getIdSalesOrder(); ?>/event/<?php echo $event ?>"
               class="button"><?php echo $event ?></a>
        <?php endforeach; ?>
    <?php else: ?>
        <?php echo __('no triggers available'); ?>
    <?php endif; ?>
</fieldset>


<?php if (!$this->order->getIsTest()): ?>
    <fieldset>
        <legend>More actions</legend>
        <a class="button" href="/sales/order/mark-as-test-order/order_id/<?php echo $this->order->getPrimaryKey() ?>">Mark
            as test order</a>
    </fieldset>
<?php endif; ?>