<?php
$tabs = Zend_Controller_Front::getInstance()->getParam('tabs');
if ($tabs) :
    foreach ($tabs as &$tabr) {
        $tabr = array(
            'current' => $this->url() === $this->url($tabr),
            'url' => $this->url($tabr)
        );
    }
?>
    <ul id="tabs">
        <?php foreach ($tabs as $title => $tab) : ?>
            <?php if ($tab['current'] === true) : ?>
                <li class="current"><?php echo $title; ?></li>
            <?php else : ?>
                <li><a href="<?php echo $tab['url']; ?>"><?php echo $title; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif;