<?php /* @var Pyz\Yves\Library\Templating\Scope\TemplateScope $this */ ?>
<?php /* @var ProjectA_Shared_Sales_Transfer_Order_Item $cartItem */ ?>

<?php $this->includePartial('response_messages', 'Application'); ?>

<pre>
    Cart-Hash: <?= $this->getString('cartHash'); ?>


<?php foreach($this->getArray('cartItems') as $cartItem): ?>

    SKU: <?= $cartItem->getSku(); ?>

    UID: <?= $cartItem->getUniqueIdentifier(); ?>

    Name: <?= $cartItem->getName(); ?>

    Quantity: <?= $cartItem->getQuantity(); ?>

    GrossPrice:             <?= $this->price()->format($cartItem->getGrossPrice()); ?>

    PriceToPay:             <?= $this->price()->format($cartItem->getPriceToPay()); ?>

    UnitGrossPrice:         <?= $this->price()->format($cartItem->getUnitGrossPrice()); ?>

    UnitPriceToPay:         <?= $this->price()->format($cartItem->getUnitPriceToPay()); ?>



<?php endforeach; ?>

    Sub Total:              <?= $this->price()->format($this->getTransfer('totals')->getSubtotal()); ?>

    Discount:              -<?= $this->price()->format($this->getTransfer('totals')->getDiscount()); ?>

    Item Expenses:         +<?= $this->price()->format($this->getTransfer('totals')->getItemExpensesTotal()); ?>

    Order Expenses:        +<?= $this->price()->format($this->getTransfer('totals')->getOrderExpensesTotal()); ?>

    Shipping Costs:        +<?= $this->price()->format($this->getTransfer('totals')->getShippingCosts()); ?>

    Tax:                   +<?= $this->price()->format($this->getTransfer('totals')->getTax()->getTotalAmount()); ?>

    --------------------------------------

    Grand Total:            <?= $this->price()->format($this->getTransfer('totals')->getGrandTotal()); ?>

</pre>
