<?php $this->renderPartial('customer/partials/sidebar'); ?>

<section class="g-4 last accountPage">
    <h2><?php echo t(Sao_Yves_Library_L::CUSTOMER_ACCOUNT_EDIT); ?></h2>

    <?php $editAccountForm->renderAsWidget(
    array('id' => 'customer-edit-form', 'enableClientValidation' => false, 'action' => $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CUSTOMER_ACCOUNT_EDIT)),
    t(Sao_Yves_Library_L::SAVE)
    ); ?>

</section>