<?php /*@var Sao_Shared_Customer_Transfer_Customer $customer */?>
    <?php //$this->renderPartial('customer/partials/sidebar'); ?>

    <section class="g-4 last accountPage">
        <h2><?php echo t(Sao_Yves_Library_L::CUSTOMER_OVERVIEW); ?></h2>
        <h3><?php echo t(Sao_Yves_Library_L::CUSTOMER_WELCOME_TITLE, array('user' => Generated_Yves_ModelFactory::getYpCustomerModelCustomer()->getName($customer))); ?></h3>
        <p><?php echo t(Sao_Yves_Library_L::CUSTOMER_WELCOME_TEXT); ?></p>
        <div class="g-2 accountInfobox">
            <h4><?php echo t(Sao_Yves_Library_L::CUSTOMER_CONTACTDATA);?></h4>
            <?php if ($customer->getSalutation() != '') : ?>
                <?php echo ($customer->getSalutation() == 'Mr') ? t(Sao_Yves_Library_L::SALUTATION_MR) : t(Sao_Yves_Library_L::SALUTATION_MRS) ; ?>
            <?php endif; ?>
            <?php echo $customer->getFirstname(); ?> <?php echo $customer->getLastname(); ?><br>
            <?php echo $customer->getEmail(); ?><br><br>

            <?php if (!isset($isFbCustomer) || !$isFbCustomer) : ?>
                <a href="<?php echo $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CUSTOMER_ACCOUNT_EDIT); ?>"><?php echo t(Sao_Yves_Library_L::CHANGE_PASSWORD); ?></a><br />
            <?php endif; ?>
            <a href="<?php echo $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CUSTOMER_ACCOUNT_EDIT); ?>" class="editAccountInfo"><?php echo t(Sao_Yves_Library_L::CUSTOMER_ACCOUNT_EDIT); ?></a>
        </div>
        <div class="g-2 accountInfobox last">
            <h4><?php echo t(Sao_Yves_Library_L::CUSTOMER_NEWSLETTER); ?></h4>
            <a href="<?php echo $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CUSTOMER_NEWSLETTER); ?>" class="editAccountInfo"><?php echo t(Sao_Yves_Library_L::EDIT); ?></a>
        </div>
        <div class="g-4 accountInfobox">
            <h4><?php echo t(Sao_Yves_Library_L::CUSTOMER_ADDRESSES); ?></h4>
            <a href="<?php echo $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CUSTOMER_ADDRESS); ?>" class="editAccountInfo"><?php echo t(Sao_Yves_Library_L::EDIT); ?></a>
            <div class="g-2">
                <strong><?php echo t(Sao_Yves_Library_L::DEFAULT_BILLING_ADDRESS); ?></strong><br />
                <?php if ($customer->getBillingAddress()): ?>
                    <?php $address = $customer->getBillingAddress(); ?>
                    <?php //echo $this->renderPartial('customer/partials/address', array('address' => $address));?>
                <?php else: ?>
                    <div><?php echo t(Sao_Yves_Library_L::NO_DEFAULT_BILLING_ADDRESS); ?></div>
                <?php endif;?>
            </div>
            <div class="g-2 last">
                <strong><?php echo t(Sao_Yves_Library_L::DEFAULT_SHIPPING_ADDRESS); ?></strong><br />
                <?php if ($customer->getShippingAddress()): ?>
                    <?php $address = $customer->getShippingAddress(); ?>
                    <?php //echo $this->renderPartial('customer/partials/address', array('address' => $address));?>
                <?php else: ?>
                    <div><?php echo t(Sao_Yves_Library_L::NO_DEFAULT_SHIPPING_ADDRESS); ?></div>
                <?php endif;?>
            </div>

        </div>

    </section>
