<hgroup>
	<h1 class="heading"><?php echo t( Sao_Yves_Library_L::NEW_BILLING_ADDRESS_HEADING ); ?></h1>
</hgroup>
<ul class="form-list">
	<li class="row">
		<div class="column">
			<label for="first-name"><?php echo t( Sao_Yves_Library_L::FIRST_NAME ); ?> *</label>
		</div>
		<div class="column">
			<input class="input-field" type="text" name="Checkout_BillingAddressForm[first_name]" id="first-name" required>
		</div>
	<li class="row">
		<div class="column">
			<label for="first-name"><?php echo t( Sao_Yves_Library_L::LAST_NAME ); ?> *</label>
		</div>
		<div class="column">
			<input class="input-field" type="text" name="Checkout_BillingAddressForm[last_name]" id="last-name" required>
		</div>
	<li class="row">
		<div class="column">
			<label for="address"><?php echo t( Sao_Yves_Library_L::STREET_ADDRESS ); ?> *</label>
		</div>
		<div class="column">
			<input class="input-field" type="text" name="Checkout_BillingAddressForm[address1]" id="address" required>
		</div>
	<li class="row">
		<div class="column">
			<label for="address-additional"><?php echo t( Sao_Yves_Library_L::STREET_ADDITIONAL ); ?></label>
		</div>
		<div class="column">
			<input class="input-field" type="text" name="Checkout_BillingAddressForm[address2]" id="address-additional">
		</div>
	<li class="row">
		<div class="column">
			<label for="city"><?php echo t( Sao_Yves_Library_L::CITY ); ?> *</label>
		</div>
		<div class="column">
			<input class="input-field" type="text" name="Checkout_BillingAddressForm[city]" id="city" required>
		</div>
	<li class="row">
		<div class="column">
			<label for="country"><?php echo t( Sao_Yves_Library_L::COUNTRY ); ?> *</label>
		</div>
		<div class="column">
			<select class="input-field" name="Checkout_BillingAddressForm[country]" id="country" required>
            <?php foreach($countries as $isoCode => $name) : ?>
                <option value="<?php echo $isoCode; ?>"><?php echo $name; ?>
            <?php endforeach; ?>
		</select>
        </div>
	<li class="row">
		<div class="column">
			<label for="region"><?php echo t( Sao_Yves_Library_L::REGION ); ?></label>
		</div>
		<div class="column">
			<input class="input-field" type="text" name="Checkout_BillingAddressForm[additional]" id="region">
		</div>
	<li class="row">
		<div class="column">
			<label for="postal"><?php echo t( Sao_Yves_Library_L::POSTAL ); ?> *</label>
		</div>
		<div class="column">
			<input class="input-field" type="text" name="Checkout_BillingAddressForm[zip_code]" id="postal" required>
		</div>
</ul>
<input type="hidden" name="Checkout_BillingAddressForm[cell_phone]" value>
