<hgroup>
    <h1 class="heading"><?php echo t( Sao_Yves_Library_L::SELECT_PAYMENT_METHOD ); ?></h1>
</hgroup>

<section class="fieldsets row active">
    <header class="column">
        <label for="payment-creditcard-new">
            <input type="radio" name="Checkout_PaymentForm[method]" value="creditcard" class="fieldset-toggle" id="payment-creditcard-new" required checked>
            <?php echo t( Sao_Yves_Library_L::PAY_WITH_CREDITCARD ); ?>
        </label>
    </header>
    <div class="column">
        <ul class="new-payment-method form-list">
            <li class="row">
                <ul class="payment-methods-list no-list horizontal-list column" id="creditcards-list">
                    <li class="ir payment-visa"><?php echo t( Sao_Yves_Library_L::PAYMENT_VISA ); ?>
                    <li class="ir payment-mastercard"><?php echo t( Sao_Yves_Library_L::PAYMENT_MASTERCARD ); ?>
                    <li class="ir payment-discover"><?php echo t( Sao_Yves_Library_L::PAYMENT_DISCOVER ); ?>
                    <li class="ir payment-amex"><?php echo t( Sao_Yves_Library_L::PAYMENT_AMEX ); ?>
                </ul>
            <li class="row only-when-active">
                <div class="column">
                    <label for="new-card-holder"><?php echo t( Sao_Yves_Library_L::CREDITCARD_HOLDER ); ?> *</label>
                </div>
                <div class="column">
                    <input type="text" class="input-field" name="Checkout_Payment_CreditcardForm[cc_cardholder]" id="new-card-holder" required>
            <li class="row only-when-active">
                <div class="column">
                    <label for="new-card-number"><?php echo t( Sao_Yves_Library_L::CREDITCARD_NUMBER ); ?> *</label>
                </div>
                <div class="column">
                    <input type="text" class="input-field" name="Checkout_Payment_CreditcardForm[cc_number]" id="new-card-number" pattern="^(4\d+|5[1-5]\d+|3(4|7)\d+|6011)" required>
                </div>
            <li class="row only-when-active">
                <div class="column">
                    <label><?php echo t( Sao_Yves_Library_L::CREDITCARD_EXPIRATION_DATE ); ?> *</label>
                </div>
                <div class="small-6 column">
                    <select class="input-field" name="Checkout_Payment_CreditcardForm[cc_expiration_month]" id="new-card-expiration-month" required>
                        <option selected value><?php echo t( Sao_Yves_Library_L::MONTH ); ?>
                        <?php for ( $i = 1; $i <= 12; $i++ ): ?>
                            <option><?php echo ( $i < 10 ? '0' . $i : $i ); ?>
                        <?php endfor; ?>
                    </select>
                </div>
                <div class="small-6 column">
                    <select class="input-field" name="Checkout_Payment_CreditcardForm[cc_expiration_year]" id="new-card-expiration-year" required>
                        <option selected value><?php echo t( Sao_Yves_Library_L::YEAR ); ?>
                        <?php $year = date( 'Y' ); ?>
                        <?php for ( $i = 0; $i <= 10; $i++ ): ?>
                            <option><?php echo $year + $i; ?>
                        <?php endfor; ?>
                    </select>
                </div>
            <li class="row only-when-active">
                <div class="column">
                    <label for="new-card-cvv"><?php echo t( Sao_Yves_Library_L::CREDITCARD_SECURITY_CODE ); ?> *</label>
                </div>
                <div class="small-5 column">
                    <input type="text" class="input-field" id="new-card-cvv" name="Checkout_Payment_CreditcardForm[cc_verification]" required>
                </div>
                <div class="small-7 column">
                    <small>
                        <a href="#"><?php echo t( Sao_Yves_Library_L::CREDITCARD_SECURITY_CODE_LINK ); ?></a>
                    </small>
                </div>
        </ul>
    </div>
</section>

<section class="fieldsets row inactive">
    <header class="column">
        <label for="payment-paypal">
            <input type="radio" name="Checkout_PaymentForm[method]" value="paypal" class="fieldset-toggle" id="payment-paypal" required>
            <?php echo t( Sao_Yves_Library_L::PAY_WITH_PAYPAL ); ?>
        </label>
    </header>
    <div class="column">
        <i class="ir payment-paypal"><?php echo t( Sao_Yves_Library_L::PAYPAL ); ?></i>
        <p class="only-when-active"><small><?php echo t( Sao_Yves_Library_L::PAYPAL_PAYMENT_DISCLAIMER ); ?></small></p>
    </div>
</section>

<input type="hidden" name="Checkout_Payment_CreditcardForm[cc_type]" value>
<input type="hidden" name="Checkout_Payment_CreditcardForm[name]" value>
