#!/bin/bash
#
# *** Project-A deployment
#
# check_for_migrations
# This script is executed on tools host after unpacking release tarball.
# It should return 0 if there are no migrations, 1 if there are any migrations pending.
#
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; . $BASEDIR/vars; source $BASEDIR/functions
outfile=`mktemp /tmp/deploy-diff-XXXXXX`

# Check for propel migrations
cd $destination_release_dir

# Remove old Propel migration files
rm -fr src/Generated/Zed/PropelGen/$APPLICATION_STORE/build/migrations

modified_text="Structure of database was modified in datasource"
same_text="Same XML and database structures"
echo "`pwd` $APPLICATION_ENV $APPLICATION_STORE"
sudo -u www-data vendor/bin/console -s ${APPLICATION_STORE} -e ${environment} propel-diff >> $outfile
cat $outfile | grep "$modified_text"
return=$?

if [ `cat $outfile | grep -c "$same_text"` -lt 1 ]; then
  if [ $return -eq 0 ]; then
    echo "Migrations have been found ..."
  else
    echo "Unable to parse output!"
    cat $outfile
    exit 2
  fi
  echo "Diff output saved: $outfile - return value: $return"
fi

echo "Diff output saved: $outfile - return value: $return"

#rm -f $outfile
exit $return
