#!/bin/bash
#
# *** Project-A deployment
#
# check_configuration
# This script is executed on all hosts after unpacking release tarball.
# It should return 0 if configuration is OK, 1 if there are any problems found.
#
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile=`mktemp /tmp/deploy-XXXXXX`

# Check for config files
if [ ! -f $shared_dir/config_local.php ]; then
  echo "ERROR: config_local.php not found"
  exit 1
fi

rm -f $outfile
exit $return
