#!/bin/bash
#
# *** Project-A deployment
#
# configure_host
# This script is executed on all hosts, after unpacking release tarball.
#
# If application needs any commands to be executed before activating release, it should be put here
# Examples: generate orm files, compile sass, setup java applications inside Tomcat
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile=`mktemp /tmp/deploy-XXXXXX`

### Generate propel files
cd $destination_release_dir
vendor/bin/console setup:deploy:prepare_propel

### Link public assets to shared static static (for relative URLs in minified stylesheets)
if is_default_store; then
  cd $destination_release_dir/data/static
  for DIR in styles scripts images fonts; do
    [ ! -e $DIR ] && ln -sf $destination_current_dir/static/public/Yves/$DIR $DIR
  done
fi

rm -f $outfile
exit 0
