#!/bin/bash
#
# *** Project-A deployment
#
# disable_maintenance
# This script is executed on all frontend hosts in order to deactivate maintenance mode.
#
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile=`mktemp /tmp/deploy-XXXXXX`

### Deactivate maintenance
if [ -d $destination_current_dir/static/public/Yves ]; then
  cd $destination_current_dir/static/public/Yves
  rm -f maintenance.html
else
  echo "ERROR - static/public/Yves not found in current release. That's fine if host is fresh."
fi

rm -f $outfile
exit 0
