#!/bin/bash
#
# 
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; . $BASEDIR/vars; source $BASEDIR/functions
outfile="/tmp/deploy-${deploy_outfile_prefix}-enable-cronjobs"
`touch $outfile`

export APPLICATION_ENV=$environment

vendor/bin/pav-console setup:jenkins:generate

rm -rf $outfile
exit 0
