#!/bin/bash
#
# *** Project-A deployment
#
# enable_maintenance
# This script is executed on all frontend hosts in order to activate maintenance mode.
#
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile=`mktemp /tmp/deploy-XXXXXX`

### Activate maintenance
if [ ! -d $destination_current_dir/project/Yves/public ]; then
  echo "Host is fresh!"
  exit
fi

# Previous release
cd $destination_current_dir/project/Yves/public
if [ -f _maintenance.html ]; then
  cp _maintenance.html maintenance.html
else
  echo 'Maintenance mode is on' > maintenance.html
fi

# New release
cd $destination_release_dir/project/Yves/public
if [ -f _maintenance.html ]; then
  cp _maintenance.html maintenance.html
else
  echo 'Maintenance mode is on' > maintenance.html
fi


rm -f $outfile
exit 0
