#!/bin/bash
#
# *** spryker deployment
#
# enable_cronjobs
# This script is executed on tools host (as $www_user user) in order to activate cronjobs
#
#

#Exit if a command exits with a non-zero status
set -e

#Exit if an uninitialised variable is used
set -o nounset

FILEPATH=`pwd`/$0
BASEDIR=`dirname $FILEPATH`
source "$BASEDIR/vars"
source "$BASEDIR/functions"
outfile=`mktemp /tmp/deploy-XXXXXX`

# Prepare Jenkins - get roles for current hosts and call console if there are any roles for current host.
cd "$destination_release_dir"
roles=`get_cronjob_roles | sed 's/\([^ ]*\)/--role \1/g'`
if [ -z "$roles" ]; then
  echo "No cronjobs on this host"
  roles="empty"
else
  echo "Installing cronjobs for roles: $roles"
fi

APPLICATION_ENV="${environment}" vendor/bin/console setup:jenkins:generate $roles
APPLICATION_ENV="${environment}" vendor/bin/console setup:jenkins:enable

rm -f "$outfile"
exit 0
