#!/bin/bash
#
# *** Project-A deployment
#
# exec_foreach_store
# This is a helper script, which executes command given as a parameter for ALL the stores
# (configuration is taken from 'stores' file')
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname "$FILEPATH"`; . $BASEDIR/stores

if [ "$1" == "-v" ]; then
  VERBOSE=1
  shift
fi

CMD=$1; shift

for X in `seq 0 $stores_array_max`; do 
  export APPLICATION_LOCALE=${locales[$X]}
  export APPLICATION_STORE=${stores[$X]}
  export APPDOMAIN=${appdomains[$X]}
  if [ $X -eq 0 ]; then
    export IS_DEFAULT_STORE=1
  else
    export IS_DEFAULT_STORE=
  fi
  [ $VERBOSE ] && echo "Executing for ${APPLICATION_STORE}: $CMD $*"
  $CMD $*
done