#!/bin/bash
#
# *** Project-A deployment
#
# exec_default_store
# This is a helper script, which executes command given as a parameter for DEFAULT store only
# (configuration is taken from 'stores' file')
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname "$FILEPATH"`; . $BASEDIR/stores

CMD=$1; shift

set -e

export APPLICATION_LOCALE=${locales[0]}
export APPLICATION_STORE=${stores[0]}
export APPDOMAIN=${appdomains[0]}
export IS_DEFAULT_STORE=1
[ "$verbose" == "true" ] && echo "Executing (default store: ${APPLICATION_STORE}): $CMD $*"
$CMD $*