#!/bin/bash
#
# *** spryker deployment
#
# exec_default_store
# This is a helper script, which executes command given as a parameter for DEFAULT store only
# (configuration is taken from 'stores' file')
#

#Exit if a command exits with a non-zero status
set -e

#Exit if an uninitialised variable is used
set -o nounset

FILEPATH=`pwd`/$0; BASEDIR=`dirname "$FILEPATH"`; . $BASEDIR/stores

CMD=$1; shift

export APPLICATION_LOCALE=${locales[0]}
export APPLICATION_STORE=${stores[0]}
export APPDOMAIN=${appdomains[0]}
export IS_DEFAULT_STORE=1
[ "$verbose" == "true" ] && echo "Executing (default store: ${APPLICATION_STORE}): $CMD $*"
$CMD $*
