#!/bin/bash
#
#
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; . $BASEDIR/vars; source $BASEDIR/functions
outfile="/tmp/deploy-${deploy_outfile_prefix}-initialize-database"
`touch $outfile`

# noop

rm -rf $outfile
exit 0