#!/bin/bash
#
# *** spryker deployment
#
# reindex_kv
# This script is executed only if deployer chooeses to, on all hosts, after unpacking release tarball, after the maintenance time.
#
#

#Exit if a command exits with a non-zero status
set -e

#Exit if an uninitialised variable is used
set -o nounset

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars
outfile=`mktemp /tmp/deploy-XXXXXX`

cd "$destination_release_dir"
vendor/bin/console collector:storage:export
rm -f "$outfile"
exit 0
