#!/bin/bash
#
# *** Project-A deployment
#
# reindex_memcache
# This script is executed only if deployer chooeses to, on all hosts, after unpacking release tarball, after the maintenance time.
#
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars
outfile=`mktemp /tmp/deploy-XXXXXX`

cd $destination_release_dir
echo "--- Reindexing memcache for store: $APPLICATION_STORE ---"
php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console storage:kv -a full -s ${APPLICATION_STORE} -e ${environment}

rm -f $outfile
exit 0
