#!/bin/bash
#
# *** Project-A deployment
#
# reindex_kv
# This script is executed only if deployer chooeses to, on all hosts, after unpacking release tarball, after the maintenance time.
#
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars
outfile=`mktemp /tmp/deploy-XXXXXX`

cd $destination_release_dir
vendor/bin/console frontend-exporter:export-key-value
rm -f $outfile
exit 0
