#!/bin/bash
#
# *** Pets-Deli deployment
#
# send_notifications_before
# This script is executed on tools host before deployment.
#

#Exit if a command exits with a non-zero status
set -e

#Exit if an uninitialised variable is used
set -o nounset

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile="/tmp/deploy-${deploy_outfile_prefix}-send-notifications-before"
`touch $outfile`

slack_msg=":no_entry: Start deployment of *${scm_path}* to release *${deploy_outfile_prefix}* in *${environment}*"
slack_msg="${slack_msg}\n Deployment started by : $deploy_user from host `/bin/hostname`"

send_slack_notification "${slack_msg}"

rm -f "$outfile"
exit 0
