#!/bin/bash
#
# send_notifications
# This script is executed on tools host after deployment.
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile="/tmp/deploy-${deploy_outfile_prefix}-send-notifications"
`touch $outfile`

slack_msg="Finished deployment of *${scm_path}* to release *${deploy_outfile_prefix}* in *${environment}*"
slack_msg="${slack_msg}\nDeployed by: $deploy_user from host `/bin/hostname`"

send_slack_notification "${slack_msg}"

rm -f $outfile
exit 0