#!/bin/bash
#
# send_notifications
# This script is executed on tools host after deployment.
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile="/tmp/deploy-${deploy_outfile_prefix}-send-notifications-after"
`touch $outfile`

### Newrelic notifications
for APP in Yves Zed; do
  app_name="$APP(${environment})"
  echo "Send deployment notification to New Relic for: $app_name .."
  vendor/bin/console newrelic:record-deployment "$app_name" "$deploy_user" "$revision" "$scm_path" "$changelog" | grep '<error>' | sed 's/^/Newrelic API:/'
done


slack_msg=":white_check_mark: Finished deployment of *${scm_path}* to release *${deploy_outfile_prefix}* in *${environment}*"
slack_msg="${slack_msg}\nDeployed by: $deploy_user from host `/bin/hostname`"

send_slack_notification "${slack_msg}"

rm -f $outfile
exit 0
