#!/bin/bash
#
# *** Project-A deployment
#
# send_notifications_before
# This script is executed on tools host before deployment.
#

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; source $BASEDIR/vars; source $BASEDIR/functions
outfile=`mktemp /tmp/deploy-XXXXXX`



### Skype notifications
#if [ "$environment" == "production" ]; then
#  curl -s -X POST --data-urlencode "M=(~) $deploy_user: Starting deployment of $scm_path to $environment ($revision, `hostname`)" "http://skypebot.project-a.com:10080/send.php?C=116&U=56&P=boss33mgj"
#elif [ "$environment" == "staging" ]; then
#  curl -s -X POST --data-urlencode "M=(~) $deploy_user: Starting deployment of $scm_path to $environment ($revision, `hostname`)" "http://skypebot.project-a.com:10080/send.php?C=116&U=56&P=boss33mgj"
#elif [ "$environment" == "testing" ]; then
#  curl -s -X POST --data-urlencode "M=(~) $deploy_user: Starting deployment of $scm_path to $environment ($revision, `hostname`)" "http://skypebot.project-a.com:10080/send.php?C=116&U=56&P=boss33mgj"
#elif [ "$environment" == "development" ]; then
#  curl -s -X POST --data-urlencode "M=(~) $deploy_user: Starting deployment of $scm_path to $environment ($revision, `hostname`)" "http://skypebot.project-a.com:10080/send.php?C=116&U=56&P=boss33mgj"
#fi

if [ "$environemt" == "production" ] && [ -n $slack_domain ] && [ -n $slack_token ] && [ -n $slack_channel ]; then
    curl -s -X POST --data-urlencode "Starting deployment of $scm_path to $environment ($revision: $deploy_user, `hostname`)" "https://$slack_domain.slack.com/services/hooks/slackbot?token=$slack_token&$slack_channel"
fi

rm -f $outfile
exit 0
