#!/bin/bash
#
# update_cdn

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; . $BASEDIR/vars; source $BASEDIR/functions
outfile="/tmp/deploy-${deploy_outfile_prefix}-update-cdn"
`touch $outfile`

export APPLICATION_ENV=$environment

cd $BASEDIR
npm run spy-setup all


rm -rf $outfile
exit 0