#!/bin/bash
#
# update_cdn

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; . $BASEDIR/vars; source $BASEDIR/functions
outfile="/tmp/deploy-${deploy_outfile_prefix}-update-cdn"
`touch $outfile`

cd $destination_current_dir
npm run spy-setup


rm -rf $outfile
exit 0