#!/bin/bash
#
# *** Project-A deployment
#
# update_cdn

FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; . $BASEDIR/vars; source $BASEDIR/functions
outfile=`mktemp /tmp/deploy-perfmig-XXXXXX`

### Copy assets to CDN
cd $destination_release_dir

echo "Distributing assets to CDN - if configured"
APPLICATION_ENV=$environment php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console cloud:publish-files -e $environment -s ${APPLICATION_STORE} &> $outfile
return=$?

echo "CDN output saved in $outfile"

if [ $return -ne 0 ]; then
  echo "CDN returned error!"
  cat $outfile
  exit $return
fi

exit 0
