<?php
// jQuery themes list:  http://www.stemkoski.com/jquery-ui-1-7-2-themes-list-at-google-code/
$this->headLink()
    ->appendStylesheet('/styles/catalog.css');

// jQuery UI versions:  http://code.google.com/apis/ajaxlibs/documentation/#jqueryUI
$this->headScript()
    ->appendFile('/scripts/modules/catalog.js');
    #->appendFile('http://cdn.jquerytools.org/1.2.7/all/jquery.tools.min.js')
    #->appendFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js');

echo $this->headLink();
echo $this->headScript();

if($this->error) {
    ProjectA_Zed_Library_FlashMessage::getInstance()->addError($this->error);
}
?>

<?php if(!$this->product) {
    echo __("invalid product");
} else { ?>

<div>
    <div class="floatLeft">
        <?
        if(!empty($this->productImages) && isset($this->productImages['cart'])) {
            echo '<img id="catalogProductImage_TopLeft" src="' . ProjectA_Shared_Library_Image::getAbsoluteProductImageUrl($this->productImages['cart']['src'], ProjectA_Shared_Library_Image::TYPE_CART) . '" />';
        } else {
            echo '<span class="paddingRight10">' . __('missing image') . '</span>';
        }
        ?>
    </div>
    <div class="floatLeft">
        <h2><?=isset($this->product['name']) ? $this->product['name'] : 'no name attribute available'?> (<?=__($this->product->getVariety())?> | <?=__($this->product->getAttributeSet()->getName())?>)</h2>
        <h4><?php echo __('current_final_price') . ": " . ProjectA_Shared_Library_Currency::format($this->product['final_gross_price']);?></h4>
        <h4><?php echo __('displayable_stock') . ": " . $this->product['displayable_stock'];?></h4>
        <h4><?php echo __('physical_stock') . ": " . $this->product['physical_stock'];?></h4>
    </div>
    <div class="floatRight marginRight10">
        <?=ProjectA_Zed_Library_Ui_Button_Factory::getCta()->setLabel(__('save'))->setClick("if(confirm('" . __('confirm save') . "')){document.catalogForm.submit();}else{return false;};")?>
        <?=ProjectA_Zed_Library_Ui_Button_Factory::get()->setLabel(__('reset'))->setClick("if(confirm('" . __('confirm reset') . "')){ document.location='/catalog/product/edit/id/" . $this->product->getProduct()->getIdCatalogProduct() . "';} else {return false;}")?>
        <?=ProjectA_Zed_Library_Ui_Button_Factory::get()->setLabel(__('leave without saving'))->setClick("if(confirm('" . __('confirm leave without saving') . "')){ document.location='/catalog/product/';} else {return false;}")?>

    </div>
    <div class="clear paddingBottom10"></div>

    <?=$this->form->renderForm($this->crud)?>

</div>

<?php }