<main id="main" class="row" role="main">
  <div class="column security-code">
    <h1 class="heading">VISA/Mastercard</h1>
    <p>The security code on a VISA/MasterCard is the last 3 digits that come after your credit card number on the back of your card.</p>
    <figure>
      <img src="<?php echo Sao_Yves_Library_Routing_UrlManager::createImageUrl( 'cc_visa.jpg' ); ?>" width="300" height="195" alt="A VISA card with the security code highlighted.">
      <figcaption>A VISA card with the security code highlighted.</figcaption>
    </figure>

    <hr>

    <h1 class="heading" id="discover">Discover Card</h1>
    <p>The security code on a Discover Card is the last 3 digits that come after your credit card number on the back of your card.</p>
    <figure>
      <img src="<?php echo Sao_Yves_Library_Routing_UrlManager::createImageUrl( 'cc_discover.jpg' ); ?>" width="300" height="195" alt="A Discover card with the security code highlighted.">
      <figcaption>A Discover card with the security code highlighted.</figcaption>
    </figure>

    <hr>

    <h1 class="heading" id="amex">American Express Card</h1>
    <p>The security code on an American Express Card is the 4 digits that are above and to the right of your credit card number on the front of your card.</p>
    <figure>
      <img src="<?php echo Sao_Yves_Library_Routing_UrlManager::createImageUrl( 'cc_amex.jpg' ); ?>" width="300" height="195" alt="An American Express card with the security code highlighted.">
      <figcaption>An American Express card with the security code highlighted.</figcaption>
    </figure>

  </div>
</main>
