<?php
/**
 * @var Sao_Yves_Checkout_Component_Form_Index $indexForm
 *
 * @var array $billingForms
 * @var Sao_Yves_Checkout_Component_Form_Billing $newBillingForm
 * @deprecated-var bool                         $billingFormId
 * @var Sao_Yves_Checkout_Component_Form_BillingAddress $billingAddressForm
 *
 * @var array $shippingForms
 * @var Sao_Yves_Checkout_Component_Form_ShippingAddress $shippingAddressForm
 * @deprecated-var bool                         $shippingFormId
 *
 * @var Sao_Yves_Checkout_Component_Form_Shipping $newShippingForm
 * @var Sao_Yves_Checkout_Component_Form_AlternativeShippingAddress $alternativeShippingAddressForm
 * @var Sao_Yves_Checkout_Component_Form_AlternativeShippingAddress $alternativeShippingAddress
 *
 * @var Sao_Yves_Checkout_Component_Form_Creditcard $paymentForm
 * @var array $paymentForms Checkout_PaymentForm
 *
 * @var Sao_Yves_Checkout_Component_Form_Agreement $agreementForm
 *
 * @var Sao_Yves_Application_Component_Form_Coupon $couponForm
 * @deprecated-var Sao_Yves_Customer_Component_Form_Login           $loginForm
 *
 * @var Sao_Shared_Sales_Transfer_Order $order
 * @var Sao_Shared_Sales_Transfer_Order $salesOrder
 * @var Sao_Shared_Sales_Transfer_Order_Item_Collection $items
 *
 * @deprecated-var bool                         $isGuest
 */

/** @see https://project-a.codebasehq.com/projects/saatchi/tickets/107 */
// $indexForm->getElement('type')->getValue();
?>

<?php $this->renderPartial(
    'checkout/index/multi-page',
    array(
        'salesOrder'                     => $salesOrder,
        'items'                          => $items,
        'couponForm'                     => null,
        'shippingAddressForm'            => $shippingAddressForm,
        'billingAddressForm'             => $billingAddressForm,
        'alternativeShippingAddressForm' => $alternativeShippingAddressForm,
        'paymentForm'                    => $paymentForm,
        'paymentForms'                   => $paymentForms,
        'countries'                      => $countries,
        'regions'                        => $regions
    )
);

// var_dump(555555555555555, $paymentForm, 555555555555555555555555, $paymentForms, array_keys($paymentForms));exit();

?>
