<form class="row single-page styled-form" action="<?php echo $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_SAVEORDER); ?>" novalidate data-js-validate>
	<!-- address -->
	<section class="column large-4 address">
		<?php $this->renderPartial('checkout/partials/shippingaddressforms', array()); ?>
		<?php $this->renderPartial('checkout/partials/billingaddressforms', array()); ?>
	</section>

	<!-- payment -->
	<section class="column large-4">
		<?php $this->renderPartial('checkout/partials/paymentmethods', array()); ?>
	</section>

	<!-- review -->
	<section class="column large-4">
		<hgroup>
			<h1 class="heading"><?php echo t( Sao_Yves_Library_L::ORDER_REVIEW_HEADING ); ?></h1>
		</hgroup>
		<input type="submit" value="<?php echo t( Sao_Yves_Library_L::SUBMIT_ORDER ); ?>" class="submit-button">
		<?php $this->renderPartial('checkout/partials/cart', array('editable' => false, 'items' => $items, 'order' => $salesOrder, 'couponForm' => $couponForm)); ?>

		<input type="submit" value="<?php echo t( Sao_Yves_Library_L::SUBMIT_ORDER ); ?>" class="submit-button">
	</section>
</form>
