<?php
/**
 * Class Description
 *
 * Date: 24.08.12
 * @author: Robert Hänsel
 * @version: $Id$
 */

$this->headScript()
    ->appendFile('/scripts/modules/jquery.jstree.js');

$categoryIds = implode(",", $this->categoryIds);

$scopeId = $this->scopeId;
$productId = $this->productId;

?>
<div id="category-container">
    <div id="category-tree-container"></div>
    <div id="category-details"></div>
</div>

<div class="loading"></div>

<script type="text/javascript">
    var treeInitialized = false;
    var scopeId = <?php echo $scopeId; ?>;
    var productId = <?php echo $productId; ?>;

    $("body").ajaxStart(function () {
        $("#main").addClass("ajax");
    });

    $("body").ajaxStop(function () {
        $("#main").removeClass("ajax");
    });

    $(function() {
        $("#category-tree-container")
            // call `.jstree` with the options object
            .jstree({
                "xml_data":{
                    "ajax":{
                        "url":"/category/index/category-name-tree?format=xml&scopeId=" + scopeId,
                        "data":function (n) {
                            return {
                                id:n.attr ? n.attr("id").replace("id_category_", "") : 0
                            };
                        }

                    },
                    "xsl":"flat"
                },
                "plugins":["themes", "xml_data", "ui", "crrm", "dnd", 'checkbox'],
                "core":{
                    "animation":0,
                    "open_parents":true
                },
                "checkbox":{
                    "two_state":true
                }
            })
            .bind("loaded.jstree", function (event, data) {
                var categoryIds = "<?php echo $categoryIds; ?>";
                var categories = categoryIds.split(",");
                $.each(categories, function (index, value) {
                    var categoryId = "#id_category_" + value;
                    $.jstree._reference("#category-tree-container").check_node(categoryId);
                });
                treeInitialized = true;
                resizeIframe();
            })
            .bind("change_state.jstree", function (event, data) {
                if (treeInitialized) {
                    // is enabled or not?
                    var isCategoryChecked = $.jstree._reference("#category-tree-container").is_checked(data.rslt[0]);
                    var categoryNameId = data.rslt[0].id.replace("id_category_", "");

                    $.ajax({
                        url:"/catalog/product/category-edit/",
                        data:{
                            mode:(isCategoryChecked ? 'add' : 'remove'),
                            categoryNameId:categoryNameId,
                            id:productId,
                            format:"json"
                        },
                        error:function (jqXHR, textStatus, errorThrown) {
                            alert("Could not save category information" + "\n" + textStatus + ": " + errorThrown);
                        }
                    });
                }
            })
            .bind("select_node.jstree", function (e, data) {
                var isCategoryChecked = $.jstree._reference("#category-tree-container").is_checked(data.rslt[0]);
                var nodeId = $(data.rslt.obj).attr("id").replace("id_category_", "");
                if (treeInitialized && nodeId) {
                    if (isCategoryChecked) {
                        var getData = {id:productId, categoryNameId:nodeId, scopeId:scopeId, format:'html'};

                        $.get('/catalog/product/category-boost',
                                getData,
                                function (data, textStatus, jqXHR) {
                                    $('#category-details').html(data);
                                }
                        );
                    } else {
                        $("#category-details").html("");
                    }
                }
            })
            .bind("open_node.jstree close_node.jstree", function (e) {
                if (treeInitialized) {
                    resizeIframe();
                }
            });
    });

    function resizeIframe() {

        var $iframe = $('iframe', window.parent.document);

        $(window.parent.document).contents().find('.tabContent:not(.active)').css({display:'table'});
        var height = $iframe.contents().find('#category-tree-container').height() + 70;
        $(window.parent.document).contents().find('.tabContent:not(.active)').css({display:'none'});

        $iframe.height(height + 'px');
    }
</script>
