<br /><br />
<div style="background-image: url(/old/images/layout/info_icon.png); background-repeat: no-repeat; padding: 0 0 0 30px;">
    Upload product descriptions by choosing a file from hard disk.<br /><br />
    <table border="0">
        <tr><td>Format:</td><td>CSV</td></tr>
        <tr><td>File encoding:</td><td>UTF-8</td></tr>
        <tr><td>Field delimiter:</td><td>,</td></tr>
        <tr><td>Field enclosure:</td><td>"</td></tr>
    </table>
    <br/><br/>
</div>

<?php echo $this->form; ?>