<?php
$itemCount = $items->count();
$productTypes = Sao_Yves_Cart_Component_Model_Helper::countProductTypes($items);
?>

<script id="checkout-step-review-cart-expenses-template" type="text/x-lodash-template">
  <% if ( totals.subtotalWithoutExpenses && !! parseInt( totals.subtotalWithoutExpenses.replace( /[^\d]/g, '' ), 10 ) ) { %>
    <dl class="cart-expenses-list">
      <dt class="strong subtotal"><?php echo t(Sao_Yves_Library_L::SUBTOTAL); ?>:
      <dd class="strong subtotal">${totals.subtotalWithoutExpenses}
      <% if (totals.taxes && totals.taxes !== '$0.00'){ %>
        <dt class="taxes"><?php echo t(Sao_Yves_Library_L::TAXES); ?>:
        <dd class="taxes">${totals.taxes}
      <% } %>
      <% if (totals.discount !== '$0.00'){ %>
        <dt class="discount"><?php echo t(Sao_Yves_Library_L::CART_DISCOUNT); ?>:
        <dd class="discount cart-discount">- ${totals.discount}
      <% } %>
      <% if (totals.freightCosts && totals.freightCosts !== '$0.00'){ %>
        <dt class="shipping-costs"><?php echo t(Sao_Yves_Library_L::SHIPPING_COSTS); ?>:
        <dd class="shipping-costs">${totals.freightCosts}
      <% } %>
        <% if (totals.customsAndDuties && totals.customsAndDuties !== '$0.00'){ %>
        <dt class="customs"><?php echo t(Sao_Yves_Library_L::CUSTOMS_AND_DUTIES); ?><?php if($productTypes['original'] > 0 && $productTypes['original'] != $itemCount){ echo '**';}?>:
        <dd class="customs">${totals.customsAndDuties}
        <% } %>
    </dl>
  <% } %>
</script>

<script id="checkout-step-review-template" type="text/x-lodash-template" data-label-for-manual-total="<?php echo t( Sao_Yves_Library_L::ORDER_REVIEW_MANUAL_SUM_INFO ); ?>">

<?php
$buttonLabels = [
    'busy'   => t(Sao_Yves_Library_L::SUBMIT_ORDER_PROCESSING),
    'idle'   => t(Sao_Yves_Library_L::SUBMIT_ORDER),
    'manual' => t(Sao_Yves_Library_L::SUBMIT_ORDER_MANUAL)
];

?>

<div class="row review-container vertical-separator split-at-7_5">
  <section class="large-7 column">
    <div class="clearfix">
      <h1 class="heading float-left"><?php echo t( Sao_Yves_Library_L::ORDER_REVIEW_HEADING ); ?></h1>
      <div class="text-right float-right">
        <a href="#step:finished" class="submit-button" <?php echo Sao_Yves_Library_Form_Html::getJsonDataAttr( 'labels', $buttonLabels ); ?>><% print( manual ? '<?php echo t( Sao_Yves_Library_L::SUBMIT_ORDER_MANUAL ); ?>' : '<?php echo t( Sao_Yves_Library_L::SUBMIT_ORDER ); ?>' ); %></a>
      </div>
    </div>

    <% if ( manual ){ %>
      <div class="manual-message">
          <p><?php echo t( Sao_Yves_Library_L::MANUAL_CONTACT_HEADER ); ?> <?php echo t( Sao_Yves_Library_L::MANUAL_CONTACT_CONTENT ); ?></p>
          <p class="small"><?php echo t( Sao_Yves_Library_L::MANUAL_CONTACT_CONTENT_2 ); ?> <span>${ shippingAddress.phoneNumber }</span><br>
              <?php echo t( Sao_Yves_Library_L::MANUAL_WRONG_NUMBER ); ?><a href="#step:shipping-address" data-route-back-to-review="shipping-address"><?php echo t( Sao_Yves_Library_L::HERE ); ?></a></p>
      </div>
    <% } %>

    <?php $this->renderPartial('cart/index/partials/cart-table', array('editable' => false, 'items' => $items, 'productTypes' => $productTypes, 'order' => $salesOrder, 'couponForm' => $couponForm, 'highlightMerged' => null, 'latestAddedProduct' => null, 'latestAddedProductShown' => null)); ?>

    <div class="text-right">
      <a href="#step:finished" class="submit-button" <?php echo Sao_Yves_Library_Form_Html::getJsonDataAttr( 'labels', $buttonLabels ); ?>><% print( manual ? '<?php echo t( Sao_Yves_Library_L::SUBMIT_ORDER_MANUAL ); ?>' : '<?php echo t( Sao_Yves_Library_L::SUBMIT_ORDER ); ?>' ); %></a>
    </div>
      <p class="small review-disclaimer">* <?php echo t(Sao_Yves_Library_L::DISCLAIMER_DELIVERY_TIME); ?></p>
      <?php if ($productTypes['original'] > 0 && $productTypes['original'] != $itemCount): ?>
      <p class="small review-disclaimer review-disclaimer-customs"> ** <?php echo t(Sao_Yves_Library_L::DISCLAIMER_CUSTOMS); ?></p>
      <?php endif;?>
  </section>
  <aside class="large-4 column">
    <section class="checkout-info-box">
      <header>
        <h1 class="heading"><?php echo t( Sao_Yves_Library_L::SHIPPING_ADDRESS ); ?></h1>
        <a href="#step:shipping-address" data-route-back-to-review="shipping-address"><?php echo t( Sao_Yves_Library_L::CHANGE_SHIPPING_ADDRESS ); ?></a>
      </header>
      <div class="vcard address">
        <p class="fn">${ shippingAddress.firstName } ${ shippingAddress.lastName }</p>
        <p class="adr">
          <span class="street-address">${ shippingAddress.address }
            <% if ( shippingAddress.addressAdditional ){ %>
              <br>${ shippingAddress.addressAdditional }
            <% } %>
          </span><br>
          <% if ( shippingAddress.region ){ %>
            <span class="region">${ shippingAddress.regionFull }</span><br>
          <% } %>
          <span class="postal-code">${ shippingAddress.postal }</span> <span class="city">${ shippingAddress.city }</span><br>
          <span class="country-name">${ shippingAddress.countryFull }</span>
        </p>
        <p class="tel">${ shippingAddress.phoneNumber }</p>
      </div>
    </section>

    <section class="checkout-info-box">
      <header>
        <h1 class="heading"><?php echo t( Sao_Yves_Library_L::BILLING_ADDRESS ); ?></h1>
        <a href="#step:billing-address" data-route-back-to-review="billing-address"><?php echo t( Sao_Yves_Library_L::CHANGE_BILLING_ADDRESS ); ?></a>
      </header>
      <div class="vcard address">
        <p class="fn">${ billingAddress.firstName } ${ billingAddress.lastName }</p>
        <p class="adr">
          <span class="street-address">${ billingAddress.address }
            <% if ( billingAddress.addressAdditional ){ %>
              <br>${ billingAddress.addressAdditional }
            <% } %>
          </span><br>
          <% if ( billingAddress.region ){ %>
            <span class="region">${ billingAddress.regionFull }</span><br>
          <% } %>
          <span class="postal-code">${ billingAddress.postal }</span> <span class="city">${ billingAddress.city }</span><br>
          <span class="country-name">${ billingAddress.countryFull }</span>
        </p>
      </div>
    </section>

    <% if ( !manual ){ %>
      <section class="checkout-info-box">
        <header>
          <h1 class="heading"><?php echo t( Sao_Yves_Library_L::PAYMENT_METHOD ); ?></h1>
          <a href="#step:payment" data-route-back-to-review="payment"><?php echo t( Sao_Yves_Library_L::CHANGE_PAYMENT_METHOD ); ?></a>
        </header>
        <% if ( payment.paymentMethod === 'paypal' ){ %>
          <div class="payment-info uses-payment-paypal">
            <p>&nbsp;<?php /* <?php echo t( L::PAYPAL ); ?>*/ ?></p>
          </div>
        <% } else { %>
          <div class="payment-info uses-payment-${ payment.detectedCard }">
            <p><% switch( payment.detectedCard ) {
              case 'visa':
                print( '<?php echo t( Sao_Yves_Library_L::PAYMENT_VISA ); ?>' );
                break;
              case 'mastercard':
                print( '<?php echo t( Sao_Yves_Library_L::PAYMENT_MASTERCARD ); ?>' );
                break;
              case 'discover':
                print( '<?php echo t( Sao_Yves_Library_L::PAYMENT_DISCOVER ); ?>' );
                break;
              case 'amex':
                print( '<?php echo t( Sao_Yves_Library_L::PAYMENT_AMEX ); ?>' );
                break;
              default:
                print( '<?php echo t( Sao_Yves_Library_L::PAYMENT_CREDITCARD ); ?>' );
            } %></p>
            <dl class="defined-payment-method">
              <dt><?php echo t( Sao_Yves_Library_L::CREDITCARD_NUMBER ); ?>:
                <dd>${ payment.cardNumberMasked }
              <dt><?php echo t( Sao_Yves_Library_L::CREDITCARD_EXPIRATION_DATE ); ?>:
                <dd>${ payment.cardExpirationMonth }
                 / ${ payment.cardExpirationYear }
            </dl>
          </div>
        <% } %>
      </section>
    <% } %>
  </aside>
</div>

<aside class="row checkout-aside">
    <div class="large-6 column">
        <?php $this->renderPartial('checkout/index/partials/shipping_providers', array()); ?>
    </div>
    <div class="large-6 column">
        <?php $this->renderPartial('checkout/index/partials/secure_payment', array()); ?>
    </div>
</aside>
</script>
