<div>
	<h1 class="heading thin">Refine Results</h1>

	<p>
		<a href="" class="checkbox checked">display art for sale only</a>
	</p>

	<section>
		<h2>Product types</h2>
		<ul class="unstyled">
			<li><a href="" class="radio checked">All</a>
			<li><a href="" class="radio">Originals</a>
			<li><a href="" class="radio">Prints</a>
		</ul>
	</section>

	<section class="expandable">
		<h2>Category</h2>
		<ul class="dropdown">
			<li><a href="">Lorem ipsum</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
		</ul>
	</section>

	<section class="expandable">
		<h2>Style</h2>
		<ul class="dropdown">
			<li><a href="">Lorem ipsum</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
		</ul>
	</section>

	<section class="expandable">
		<h2>Subject</h2>
		<ul class="dropdown">
			<li><a href="">Lorem ipsum</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
		</ul>
	</section>

	<section class="expandable">
		<h2>Location</h2>
		<ul class="dropdown">
			<li><a href="">Lorem ipsum</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
		</ul>
	</section>

	<section class="expandable">
		<h2>Price</h2>
		<ul class="dropdown">
			<li><a href="">Lorem ipsum</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
		</ul>
	</section>

	<section class="expandable">
		<h2>Orientation</h2>
		<ul class="dropdown">
			<li><a href="">Lorem ipsum</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
		</ul>
	</section>

	<section class="expandable">
		<h2>Size</h2>
		<ul class="dropdown">
			<li><a href="">Lorem ipsum</a>
			<li><a href="">foo</a>
			<li><a href="">bar</a>
			<li><a href="">baz</a>
		</ul>
	</section>

	<form class="select-container">
		<div class="select"><select><option>Category</select></div>
		<div class="select"><select><option>Style</select></div>
		<div class="select"><select><option>Subject</select></div>
		<div class="select"><select><option>Location</select></div>
		<div class="select"><select><option>Price</select></div>
		<div class="select"><select><option>Orientation</select></div>
		<div class="select"><select><option>Size</select></div>
	</form>

</div>
