<?php echo $this->doctype('XHTML5'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <link href="/images/favicon.ico" rel="shortcut icon" />
    <title>SaatchiOnline's Generated_Yves_Zed (<?php echo APPLICATION_ENV ?>)</title>
    <?php echo $this->partial('Partials/include.phtml', array()); ?>
    <script src="/old/scripts/modules/raster.js"></script>
</head>
<body>
    <script type="text/javascript">
        <?php $request = Zend_Controller_Front::getInstance()->getRequest(); ?>
        zed.vars.exchange.page.current.module = '<?php echo $request->getParam('module'); ?>';
        zed.vars.exchange.page.current.controller = '<?php echo $request->getParam('controller'); ?>';
        zed.vars.exchange.page.current.action = '<?php echo $request->getParam('action'); ?>';
        zed.modules.documentation.vars.loaded = null;
    </script>

    <section id="env_<?php echo APPLICATION_ENV ?>">
        <?php echo $this->partial('Partials/header.phtml', array()); ?>
        <div id="raster">
            <?php echo $this->layout()->content; ?>
        </div>
    </section>

    <footer><div class="actions"></div></footer>
    <div id="shortcuts"><div class="wrapper"></div></div>
    <div id="guiMessage"><div class="text"></div></div>
</body>
</html>
