<table class="item-history-table">
    <?php if (null === $this->itemHistory) : ?>
        <tr>
            <th>
                <?php echo __('no history available'); ?>
            </th>
        </tr>
    <?php else : ?>
        <?php $count = count($this->itemHistory); ?>
        <?php $status = $this->itemHistory[0]; ?>
        <?php $start = 1; ?>

        <tr class="current-status">
            <td colspan="2"><span class="bold">
                    <span class="collapseable-inverse"><?php echo __('current status'); ?></span>
                    <span class="collapseable"><?php echo __('full history'); ?></span>
                </span>:
                (<a><span class="collapseable-inverse"><?php echo __('click to view full history'); ?></span>
                    <span class="collapseable"><?php echo __('click to hide full history'); ?></span>
                </a>)
            </td>
        </tr>
        <?php if($status['status'] !== $this->currentStatus): $start = 0;?>
            <tr class="current-status">
            <th colspan="2"><?php echo $this->currentStatus; ?> (forced)</th>
        </tr>
        <?php else: ?>
        <tr class="current-status">
            <th>
                <?php echo $count; ?>. <?php echo $status['status']; ?></th>
            <td><?php echo ProjectA_Shared_Library_Date::dateTime($status['created_at']); ?></td>
        </tr>
        <?php endif; ?>
        <?php for ($i = $start; $i < $count; $i++) : ?>
            <?php $status = $this->itemHistory[$i]; ?>
            <tr class="collapseable">
                <th>
                    <?php echo $count - $i; ?>. <?php echo $status['status']; ?></th>
                <td><?php echo ProjectA_Shared_Library_Date::dateTime($status['created_at']); ?></td>
            </tr>
        <?php endfor; ?>

    <?php endif; ?>
</table>
