<?php
$item = $this->item;
$product = $this->product;
$options = $item->getOptions();
$expenses = $item->getExpenses();
$rowSpan = 2 + count($options) + count($expenses);

?>


<table class="item-info-table">
    <thead>
    <tr>
        <th colspan="2"><?php echo __('product'); ?></th>
        <th><?php echo __('gross price'); ?></th>
        <th><?php echo __('discount'); ?></th>
        <th><?php echo __('price to pay'); ?></th>
    </tr>
    </thead>
    <tr>
        <td>
            <img
                src=" <?php echo $this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_ART_TINY_CROP] ?>">
        </td>
        <td>
            <p><?php echo $item->getName(); ?></p>
            <ul>
                <?php $verification = $this->partial('statusoverview/verification.phtml', array('item' => $item, 'product' => $this->product)); ?>
                <?php if ($verification) : ?>
                    <li>
                        <?php echo $verification; ?>
                    </li>
                <?php endif; ?>
                <li>
                    <a href="/catalog/index/show/sku/<?php echo $item->getSku(); ?>"><?php echo $item->getSku(); ?></a>
                </li>
                <li>
                    <a target="_blank"
                       href="http://www.saatchionline.com<?php echo $product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_URL]; ?>"><?php echo __('view on'); ?>
                        saatchionline.com</a></li>

                <?php if ((float)$this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_HEIGHT] > 0): ?>
                    <li>
                        <?php echo __('dimensions:'); ?><br>
                        <?php echo number_format((float)$this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_HEIGHT], 2); ?>
                        x
                        <?php echo number_format((float)$this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_WIDTH], 2); ?>
                        x
                        <?php echo number_format((float)$this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_DEPTH], 2); ?> <?php echo $this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_SIZE_UNIT]; ?>
                    </li>
                <?php endif; ?>
                <?php if ((float)$this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_WEIGHT] > 0): ?>
                    <li>
                        <?php echo __('weight:'); ?><br>
                        <?php echo number_format((float)$this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_WEIGHT], 2); ?> <?php echo $this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_SHIP_WEIGHT_UNIT]; ?>
                    </li>
                <?php endif; ?>
                <?php if ($this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_PRODUCT_NAME] > 0): ?>
                    <li>
                        <?php echo __('product:'); ?><br>
                        <?php echo $this->product[Sao_Shared_Library_Catalog_Interface_ProductAttributeConstant::ATTRIBUTE_PRODUCT_NAME]; ?>
                    </li>
                <?php endif; ?>
            </ul>


        </td>
        <td><?php echo ProjectA_Shared_Library_Currency::format($item->getGrossPrice()); ?></td>
        <?php echo $this->partial('statusoverview/discount.phtml', array('discounts' => $item->getDiscounts())); ?>
        <td class="total" rowspan="<?php echo $rowSpan; ?>">
            <b><?php echo ProjectA_Shared_Library_Currency::format($item->getPriceToPay()); ?></b>
        </td>
    </tr>
    <?php echo $this->partial('statusoverview/options.phtml', array('options' => $options)); ?>
    <?php echo $this->partial('statusoverview/expenses.phtml', array('expenses' => $expenses)); ?>
</table>