<?php /** @var $option ProjectA_Zed_Sales_Persistence_PacSalesOrderItemOption */ ?>
<?php if (count($this->options) > 0) : ?>
    <?php foreach ($this->options as $option) : ?>
        <tr class="row-with-span">
            <td colspan="2"> + <?php echo $option->getName() ?> (option)</td>
            <td><?php echo ProjectA_Shared_Library_Currency::format($option->getGrossPrice()) ?></td>
            <?php echo $this->partial('statusoverview/discount.phtml', array('discounts' => $option->getDiscounts())); ?>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>