<h2 class="heading"><?php echo t( Sao_Yves_Library_L::SECURE_PAYMENT_HEADING ); ?></h2>
<ul class="logos-list no-list horizontal-list">
  <li class="perk-with-label"><i class="ir secure-ssl" title="<?php echo t( Sao_Yves_Library_L::SECURE_SSL ); ?>"><?php echo t( Sao_Yves_Library_L::SECURE_SSL ); ?></i> <?php echo t( Sao_Yves_Library_L::SECURE_SSL ); ?>
  <li class="perk-with-label"><i class="ir secure-guarantee" title="<?php echo t( Sao_Yves_Library_L::MONEY_BACK_GUARANTEE ); ?>"><?php echo t( Sao_Yves_Library_L::MONEY_BACK_GUARANTEE ); ?></i> <?php echo t( Sao_Yves_Library_L::MONEY_BACK_GUARANTEE ); ?>
</ul>
