<h2 class="heading"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDERS ); ?></h2>
<ul class="logos-list no-list horizontal-list">
  <li class="ir logo-dhl" title="<?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_DHL ); ?>"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_DHL ); ?>
  <li class="ir logo-fedex" title="<?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_FEDEX ); ?>"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_FEDEX ); ?>
  <li class="ir logo-ups" title="<?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_UPS ); ?>"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_UPS ); ?>
</ul>
