<?php
/**
 * @var Sao_Shared_Sales_Transfer_Order_Item_Collection $items
 * @var bool                                 $highlightMerged bool
 * @var bool                                 $latestAddedProductShown
 * @var string                               $latestAddedProduct
 */

if (!$editable) {
    $urlPrefix = 'https:';
} else {
    $urlPrefix = 'http:';
}

?>
<table class="cart-table">
  <thead>
    <tr>
      <th colspan="2"><?php echo t( Sao_Yves_Library_L::CART_TABLE_HEADING_ITEM ); ?>
      <th><?php echo t( Sao_Yves_Library_L::CART_TABLE_HEADING_PRICE ); ?>
      <th><?php echo t( Sao_Yves_Library_L::CART_TABLE_HEADING_QUANTITY ); ?>
      <th><?php echo t( Sao_Yves_Library_L::CART_TABLE_HEADING_SUBTOTAL ); ?>
  <tbody>
    <?php foreach($items as $item) :
        /* @var $item Sao_Shared_Sales_Transfer_Order_Item */
        /* @var $order Sao_Shared_Sales_Transfer_Order */
        $price = $item->getGrossPrice();

        /* @var $option Sao_Shared_Sales_Transfer_Order_Item_Option */
        $optionsAsLiString = '';
        foreach ($item->getOptions() as $option) {
            $price += $option->getGrossPrice();
            $prefix = ($option === ProjectA_Shared_Catalog_Interface_ProductOptionTypeConstant::OPTION_TYPE_WRAP) ? 'on' : 'including';
            $optionsAsLiString .= $prefix . ' ' . $option->getName() . '<br>';
        }

        $highlightMergedItem = $highlightMerged && $item->getIsMerged();
        $cssClassMerged = ($highlightMergedItem || (!$latestAddedProductShown && $latestAddedProduct == $item->getUniqueIdentifier())) ? 'merged' : '';
    ?>
        <tr class="cart-item <?= $cssClassMerged ?>">
          <td class="item-image" rowspan="2"><img src="<?php echo $urlPrefix . $item->getProduct()->getArtTinyCrop(); ?>" alt="<?php echo $item->getName(); ?>">
          <td class="item-description">
            <dl>
                <?php /* @var $item Sao_Shared_Sales_Transfer_Order_Item */ ?>
              <dt><a href="<?php echo $item->getProduct()->getUrl(); ?>"><?php echo $item->getName(); ?></a>
                <dd>by <?php echo $item->getProduct()->getArtistFirstName() .' '.$item->getProduct()->getArtistLastName(); ?>
                <dd class="art-description">
                    <?php echo ($item->getProduct()->getProductCategory() == 'limited edition') ? 'Limited Edition ' : '';?>
                    <?php echo $item->getProduct()->getProductName(); ?>
                    <?php if ($optionsAsLiString): ?>
                <dd class="item-options">
                        <?php echo $optionsAsLiString; ?>
                        <?php endif; ?>
            </dl>
          <td class="item-price"><?php echo price($price); ?>
          <?php if ( $editable && $item->getProduct()->getProductCategory() !== Sao_Shared_Catalog_Interface_ProductCategoryConstant::CATEGORY_ORIGINAL ): ?>
            <td class="item-quantity editable">
              <form class="styled-form qty-form" method="get" action="<?php echo $this->createAbsoluteUrl( Sao_Yves_Library_Routing_UrlManager::ROUTE_CART_QTY ); ?>">
                <input type="number" class="input-field" step="1" name="qty" min="0" value="<?php echo $item->getQuantity(); ?>" required>
                <input type="hidden" class="input-field" name="unique-identifier" value="<?php echo $item->getUniqueIdentifier(); ?>" />
                <input type="hidden" class="input-field" name="sku" value="<?php echo $item->getSku(); ?>" />
                <input type="submit" value="<?php echo t( Sao_Yves_Library_L::CART_ITEM_UPDATE ); ?>" class="visuallyhidden">
              </form>
          <?php else: ?>
            <td class="item-quantity fixed"><?php echo $item->getQuantity(); ?>
          <?php endif; ?>
        <td class="item-subtotal"><?php echo price($price * $item->getQuantity()); ?>
            <?php // $discountSum = $item->getTotalDiscountOnItem(); ?>
            <?php //if ($discountSum): ?>
            <?php // <p class="cart-discount">-  ?>
            <?php // echo price($item->getQuantity() * $item->getTotalDiscountOnItem()) </p>?>
            <?php // endif; ?>
        </td>
          <tr class="cart-item complimentary">
            <?php if ( $editable ): ?>
            <td class="item-actions <?= $cssClassMerged ?>"><a href="<?php echo $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CART_DELETE) ?>?sku=<?php echo $item->getSku(); ?>&unique-identifier=<?php echo $item->getUniqueIdentifier(); ?>"><?php echo t( Sao_Yves_Library_L::CART_ITEM_REMOVE ); ?></a>
            <?php else: ?>
            <td></td>
            <?php endif; ?>
            <td class="item-delivery-info <?= $cssClassMerged ?>" colspan="3">This item usually ships within <mark><?php echo Sao_Yves_Order_Component_Model_Fulfillment::getShippingEstimateForItem($item); ?></mark> business days.*
        <tr class="cart-item-divider">
          <td colspan="5"><hr>
     <?php endforeach; ?>
  <tfoot>

  <?php
  $itemCount = $items->count();
  ?>
  <?php if (!$editable): ?>
  <?php if ($itemCount != $productTypes['original']): ?>
  <tr class="cart-expenses-disclaimer">
      <td colspan="5">
          <small><?php echo t(Sao_Yves_Library_L::CART_ADDITIONAL_COSTS_DISCLAIMER); ?></small>
          <?php endif; ?>
          <?php endif; ?>
      <?php
      /** @var Sao_Shared_Sales_Transfer_Totals $totals */
      /** @var Sao_Shared_Sales_Transfer_Order $order */
      $totals = $order->getTotals();
      ?>
      <tr class="cart-expenses-container">
          <th colspan="1">
              <td colspan="4"
                  id="cart-expenses-container-content"<?php if (!$editable): ?><% if (manual) { %> class="manual"<% } %><?php endif; ?>>
                  <?php if ($totals->getGrandTotal() != $totals->getSubtotalWithoutItemExpenses()): ?>
                  <dl class="cart-expenses-list">
                      <dt class="strong subtotal"><?php echo t(Sao_Yves_Library_L::SUBTOTAL); ?>:
                      <dd class="strong subtotal"><?php echo price($totals->getSubtotalWithoutItemExpenses()); ?>
                          <?php if ($totals->getStateTaxAmount()) : ?>
                      <dt class="taxes"><?php echo t(Sao_Yves_Library_L::TAXES); ?>:
                      <dd class="taxes"><?php echo price($totals->getStateTaxAmount()); ?>
                          <?php endif; ?>
                          <?php if ($totals->getDiscount()): ?>
                      <dt class="discount"><?php echo t(Sao_Yves_Library_L::CART_DISCOUNT); ?>:
                      <dd class="discount cart-discount">- <?php echo price($totals->getDiscount()); ?>
                          <?php endif; ?>
                          <?php if ($totals->getFreightCosts()): ?>
                      <dt class="shipping-costs"><?php echo t(Sao_Yves_Library_L::SHIPPING_COSTS); ?>:
                      <dd class="shipping-costs"><?php echo price($totals->getFreightCosts()); ?>
                          <?php endif; ?>
                          <?php if ($totals->getCustomsAndDuties()): ?>
                      <dt class="shipping-costs"><?php echo t(Sao_Yves_Library_L::CUSTOMS_AND_DUTIES); ?><?php if($productTypes['original'] > 0 && $productTypes['original'] != $itemCount){ echo '**';}?>:
                      <dd class="shipping-costs"><?php echo price($totals->getCustomsAndDuties()); ?>
                          <?php endif; ?>
                  </dl>
      <?php endif; ?>
    <tr class="cart-total-container cart-expenses-container">
      <th colspan="2">
      <th><?php echo t( Sao_Yves_Library_L::CART_TOTAL ); ?>:
        <td class="cart-total" colspan="2" id="cart-total-grand-total"><?php echo price($totals->getGrandTotal()); ?>

    <?php if ( $editable ): ?>
    <?php /** @var $couponForm Sao_Yves_Application_Component_Form_Coupon */?>
      <tr class="voucher-container">
          <td colspan="5"<?php if ($couponForm->getElement('remove')->getValue()):?> class="has-code"<?php endif;?>>
              <?php $cActiveForm = $this->beginWidget('CActiveForm', array('htmlOptions' => array('class' => 'styled-form voucher-form'), 'action' => $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CART_ADD_COUPON))); ?>
              <?php echo $couponForm->render($cActiveForm); ?>
              <input type="submit"
                     value="<?php echo ($order->getCouponCode()) ? t(Sao_Yves_Library_L::CART_REMOVE_COUPON_CODE) : t(Sao_Yves_Library_L::CART_ADD_COUPON_CODE); ?>"
                     class="button">
              <?php $this->endWidget(); ?>
          </td>
      </tr>
    <?php endif; ?>
</table>
