<aside class="column perks vertical large-3">
  <h1 class="heading"><?php echo t( Sao_Yves_Library_L::WHY_BUY_HEADING ); ?></h1>
  <ul class="perks-list unstyled">
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_BUY_REASON_1 ); ?>
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_BUY_REASON_2 ); ?>
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_BUY_REASON_3 ); ?>
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_BUY_REASON_4 ); ?>
  </ul>

  <h2 class="heading"><?php echo t( Sao_Yves_Library_L::PAYMENT_METHODS ); ?></h2>
  <ul class="logos-list no-list horizontal-list">
    <li class="ir payment-visa" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_VISA ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_VISA ); ?>
    <li class="ir payment-mastercard" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_MASTERCARD ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_MASTERCARD); ?>
    <li class="ir payment-paypal" title="<?php echo t( Sao_Yves_Library_L::PAYPAL ); ?>"><?php echo t( Sao_Yves_Library_L::PAYPAL ); ?>
    <li class="ir payment-discover" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_DISCOVER ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_DISCOVER ); ?>
    <li class="ir payment-amex" title="<?php echo t( Sao_Yves_Library_L::PAYMENT_AMEX ); ?>"><?php echo t( Sao_Yves_Library_L::PAYMENT_AMEX ); ?>
  </ul>

  <h2 class="heading"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDERS ); ?></h2>
  <ul class="logos-list no-list horizontal-list">
    <li class="ir logo-dhl" title="<?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_DHL ); ?>"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_DHL ); ?>
    <li class="ir logo-fedex" title="<?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_FEDEX ); ?>"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_FEDEX ); ?>
    <li class="ir logo-ups" title="<?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_UPS ); ?>"><?php echo t( Sao_Yves_Library_L::SHIPPING_PROVIDER_UPS ); ?>
  </ul>

  <h2 class="heading"><?php echo t( Sao_Yves_Library_L::SECURE_PAYMENT_HEADING ); ?></h2>
  <ul class="logos-list no-list horizontal-list">
    <li class="perk-with-label"><i class="ir secure-ssl" title="<?php echo t( Sao_Yves_Library_L::SECURE_SSL ); ?>"><?php echo t( Sao_Yves_Library_L::SECURE_SSL ); ?></i> <?php echo t( Sao_Yves_Library_L::SECURE_SSL ); ?>
    <li class="perk-with-label"><i class="ir secure-guarantee" title="<?php echo t( Sao_Yves_Library_L::MONEY_BACK_GUARANTEE ); ?>"><?php echo t( Sao_Yves_Library_L::MONEY_BACK_GUARANTEE ); ?></i> <?php echo t( Sao_Yves_Library_L::MONEY_BACK_GUARANTEE ); ?>
  </ul>
</aside>
