<?php
    /**
     * @var Sao_Yves_Transactionstatus_Module_Controller_Index             $this
     * @var Sao_Yves_Checkout_Component_Form_Index          $indexForm
     * @var bool                        $highlightMerged
     * @var Sales_Order_Item_Collection $cartItemsMerged
     * @var Sao_Shared_Sales_Transfer_Order        $order
     * @var bool                        $latestAddedProductShown
     * @var string                      $latestAddedProduct
     */

    /** @var $cartModel Sao_Yves_Cart_Component_Model_Cart */
    $cartModel = $this->cart;

    $shippingAmount = $cartModel->getExpenseAmountFromOrderByType();
    $shippingIsCalculated = $cartModel->isExpenseCalculatedByType();

    $itemCount = $items->count();
    $productTypes = Sao_Yves_Cart_Component_Model_Helper::countProductTypes($items);
?>

<?php $messages = $this->getMessages(); ?>
<?php if ($messages): ?>
    <div class="row large-9">
        <section class="messages column">
            <?php foreach ($messages AS $message): ?>
                <div class="message <?php echo $message['type']; ?>">
                    <?php echo t($message['text']); ?>
                </div>
            <?php endforeach; ?>
        </section>
    </div>
<?php endif; ?>


<?php if ((isset($items) && $items->count() > 0) || !empty($itemsOutOfStock)): ?>
  <div class="row">
    <section class="large-9 column cart-container">
      <div class="text-right cart-links-bar">
        <a href="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_LEGACY_BUY_ART); ?>"
           class="continue-shopping-link link-back"><?php echo t( Sao_Yves_Library_L::CONTINUE_SHOPPING ); ?></a>
        <a href="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CHECKOUT); ?>" class="submit-button"><?php echo t( Sao_Yves_Library_L::PROCEED_TO_CHECKOUT ); ?></a>

        <!--
        <?php /** @see https://project-a.codebasehq.com/projects/saatchi/tickets/107 */ ?>
            <form action="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CHECKOUT); ?>" method="post">
              <?php echo ProjectA_Yves_Library_Yii::app()->getRequest()->getCsrfInputField(); ?>
              <input type="hidden" name="Checkout_IndexForm[type]" value="option1">
              <input type="submit" value="Submit with type=option1">
            </form>
            <a href="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CHECKOUT); ?>?Checkout_IndexForm[type]=option1">To checkout with type-param</a>
        -->
      </div>
      <div class="messages">
        <?php if($highlightMerged && count($cartItemsMerged)): ?>
          <p class="message info has-icon"><?php echo t( Sao_Yves_Library_L::CART_MERGE ); ?></p>
        <?php endif; ?>
      </div>
      <?php
      $this->renderPartial('cart/index/partials/cart-table', array(
          'editable' => true,
          'items' => $items,
          'order' => $order,
          'couponForm' => $couponForm,
          'productTypes' => $productTypes,
          'highlightMerged' => $highlightMerged,
          'latestAddedProduct' => $latestAddedProduct,
          'latestAddedProductShown' => $latestAddedProductShown
      ));
      ?>
      <div class="text-right cart-links-bar">
        <a href="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_LEGACY_BUY_ART); ?>"
           class="continue-shopping-link link-back"><?php echo t( Sao_Yves_Library_L::CONTINUE_SHOPPING ); ?></a>
        <a href="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CHECKOUT); ?>" class="submit-button"><?php echo t( Sao_Yves_Library_L::PROCEED_TO_CHECKOUT ); ?></a>
      </div>
        <p class="small review-disclaimer">* <?php echo t(Sao_Yves_Library_L::DISCLAIMER_DELIVERY_TIME); ?></p>
        <?php if ($productTypes['original'] > 0 && $productTypes['original'] != $itemCount): ?>
            <p class="small review-disclaimer review-disclaimer-customs"> <?php if ($order->getTotals()->getCustomsAndDuties() > 0): ?>** <?php endif; ?><?php echo t(Sao_Yves_Library_L::DISCLAIMER_CUSTOMS); ?></p>
        <?php endif;?>
    </section>
    <?php $this->renderPartial('cart/index/partials/sidebar-vertical', array()); ?>
  </div>
<?php else: ?>

  <div class="row">
    <p><?php echo t( Sao_Yves_Library_L::EMPTY_CART_TEXT ); ?></p>
    <p><a href="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_LEGACY_BUY_ART); ?>"
          class="submit-button"><?php echo t( Sao_Yves_Library_L::CONTINUE_SHOPPING ); ?></a></p>
  </div>

<?php endif; ?>

<?php

Sao_Yves_Library_Assets_Manager::getInstance()->addJsFile(
  'vendor/require',
  array(
    'data-main'       => Sao_Yves_Library_Routing_UrlManager::createScriptUrl( 'saatchi' ),
    'data-controller' => 'cart'
  )
);
