<header class="zed:header clearfix">
    <h1 class="zed:logo">
        <a href="/">
            <img src="/new/images/zed.png" alt="zed" title="zed">
        </a>
    </h1>

    <?php if (ProjectA\Zed\Auth\Component\Model\Auth::getInstance()->hasIdentity() || APPLICATION_ENV === 'development'): ?>

    <h2 class="zed:header__welcome">
        Welcome, <b>
        <?php if (ProjectA\Zed\Auth\Component\Model\Auth::getInstance()->hasIdentity()): ?>
            <?php $identity = ProjectA\Zed\Auth\Component\Model\Auth::getInstance()->getIdentity(); echo $identity->getFirstname() . ' ' . $identity->getLastname(); ?>
        <?php else : ?>
            Developer
        <?php endif; ?>
        </b>

        <!-- what about the logout !? it is missing in the zedgui index.html sample file
        <?php $logout = $this->navigation()->getContainer()->findOneById('login-logout'); ?>
        <a href="/<?php echo $logout->getModule() . '/' . $logout->getController() . '/logout'; ?>" class="logout"></a>
        -->
    </h2>

    <nav class="zed:header__nav">
        <?php if (ProjectA\Zed\Auth\Component\Model\Auth::getInstance()->hasIdentity()): ?>
            <?php $this->navigation()->getContainer()->findOneById('login-logout')->setVisible(false); ?>
        <?php endif; ?>
        <?php $this->navigation()->getContainer()->findOneById('setup-index')->setVisible(APPLICATION_ENV !== 'production') ?>
        <?php echo $this->navigation()->menu(); ?>
    </nav>

    <div class="zed:header__language-picker has-more">
        <i class="flag-<?php echo strtolower(ProjectA_Shared_Library_Store::getInstance()->getStoreName()) ?>"></i>
        <ul>
            <li><a href="#" class="flag-pl"></a>
            <li><a href="#" class="flag-de"></a>
            <li><a href="#" class="flag-us"></a>
        </ul>
    </div>

    <div class="zed:header__environment">
        <i class="icon-cogs"></i>
        <span><?php echo APPLICATION_ENV; ?></span>
        <dl>
            <dt>Locale:
            <dd><?php echo ProjectA_Shared_Library_Store::getInstance()->getCurrentLocale(); ?>
            <dt>Store:
            <dd><?php echo ProjectA_Shared_Library_Store::getInstance()->getStoreName(); ?>
            <dt>Server:
            <dd><?php echo ProjectA\Shared\Library\System::getHostName(); ?>
            <dt>Controller:
            <dd><?php echo $this->currentController ?>
        </dl>
    </div>

    <?php endif; ?>
</header>
