<?php


Sao_Yves_Library_Assets_Manager::getInstance()->addJsFile(
  'vendor/require',
  array(
    'data-main'       => Sao_Yves_Library_Routing_UrlManager::createScriptUrl( 'saatchi' ),
    'data-controller' => 'availability'
  )
);

?>
<div class="row checkout-address-container">
    <section class="large-6 column">
        <hgroup>
            <h1 class="heading"><?php echo t(Sao_Yves_Library_L::ARTWORK_AVAILABILITY_HEADING); ?></h1>
            <h2 class="sub-heading"><?php echo t(Sao_Yves_Library_L::REQUIRED_FIELDS_INFO); ?></h2>
        </hgroup>
        <form action="<?php echo $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_ARTIST_ARTWORK_AVAILABILITY); ?>" method="post" id="availability-form" class="styled-form address-form" data-js-validate>
            <?php echo CHtml::hiddenField('YII_CSRF_TOKEN', ProjectA_Yves_Library_Yii::app()->request->csrfToken); ?>
            <?php echo CHtml::hiddenField('hash', $form->hash); ?>
            <ul class="form-list">
                <li class="row">
                    <div class="large-offset-4 large-8 column">
                        <label for="artwork-availability">
                          <input class="input-field" type="radio" name="artwork_availability" value="1" id="artwork-availability" data-trigger-on-load="change" data-error-label="<?php echo t(Sao_Yves_Library_L::ARTWORK_AVAILABLE); ?>" <?php echo Sao_Yves_Library_Form_Html::getCheckedIf($form->artwork_availability, 1) ?>>
                          <?php echo t(Sao_Yves_Library_L::ARTWORK_AVAILABLE); ?> *
                        </label>
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('artwork_availability'), 'artwork_availability') ?>
                    </div>
                <li class="row">
                    <div class="large-offset-4 large-8 column">
                        <label for="artwork-availability2">
                          <input class="input-field" type="radio" name="artwork_availability" value="0" id="artwork-availability2" data-error-label="<?php echo t(Sao_Yves_Library_L::ARTWORK_NOT_AVAILABLE); ?>" <?php echo Sao_Yves_Library_Form_Html::getCheckedIf($form->artwork_availability, 0) ?>>
                          <?php echo t(Sao_Yves_Library_L::ARTWORK_NOT_AVAILABLE); ?> *
                        </label>
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('artwork_availability'), 'artwork_availability') ?>
                    </div>
                <li class="row">
                    <div class="small-4 column">
                        <label for="address-first-name"><?php echo t(Sao_Yves_Library_L::FIRST_NAME); ?>: *</label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="first_name" id="address-first-name" required data-error-label="<?php echo t(Sao_Yves_Library_L::FIRST_NAME_ERROR); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->first_name) ?> maxlength="100">
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('first_name'), 'first-name') ?>
                    </div>
                <li class="row">
                    <div class="small-4 column">
                        <label for="address-first-name"><?php echo t(Sao_Yves_Library_L::LAST_NAME); ?>: *</label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="last_name" id="address-last-name" required data-error-label="<?php echo t(Sao_Yves_Library_L::LAST_NAME_ERROR); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->last_name) ?> maxlength="100">
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('last_name'), 'last-name') ?>
                    </div>
                <li class="row">
                    <div class="small-4 column">
                        <label for="address-address"><?php echo t(Sao_Yves_Library_L::STREET_ADDRESS); ?>: *</label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="address1" id="address-address" required data-error-label="<?php echo t(Sao_Yves_Library_L::STREET_ADDRESS_ERROR); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->address1) ?> maxlength="255" data-min-length="2" data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_ADDRESS1_MIN_LENGTH); ?>">
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('address1'), 'address') ?>
                    </div>
                <li class="row">
                    <div class="small-4 column">
                        <label for="address-address-additional"><?php echo t(Sao_Yves_Library_L::STREET_ADDITIONAL); ?></label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="address2" id="address-address-additional" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->address2) ?>>
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('address2'), 'address-additional') ?>
                    </div>
                <li class="row">
                    <div class="small-4 column">
                        <label for="address-city"><?php echo t(Sao_Yves_Library_L::CITY); ?>: *</label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="city" id="address-city" required data-error-label="<?php echo t(Sao_Yves_Library_L::CITY_ERROR); ?>" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->city) ?> maxlength="255" data-min-length="2" data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_CITY_MIN_LENGTH); ?>">
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('city'), 'city') ?>
                    </div>
                <li class="row">
                    <div class="small-4 column">
                        <label for="address-country"><?php echo t(Sao_Yves_Library_L::COUNTRY); ?>: *</label>
                    </div>
                    <div class="small-8 column">
                        <select class="input-field" name="country" id="address-country" required data-trigger-on-load="change" data-error-label="<?php echo t(Sao_Yves_Library_L::COUNTRY_ERROR); ?>">
                            <?php foreach ($countries as $isoCode => $name) : ?>
                            <option
                                value="<?php echo $isoCode; ?>" <?php echo Sao_Yves_Library_Form_Html::getSelectedIf($form->country, $isoCode); ?>><?php echo $name; ?>
                                <?php endforeach; ?>
                        </select>
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('country'), 'country') ?>
                    </div>
                <li class="row" data-bound-by="address_country" data-bound-by-value="*">
                    <div class="small-4 column">
                        <label for="address-region"><?php echo t(Sao_Yves_Library_L::REGION); ?></label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="region" id="address-region" <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->region) ?> >
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('region'), 'region') ?>
                    </div>
                    <?php foreach ($regions as $iso => $regionsArray): ?>
                <li class="row hidden" data-bound-by="address_country" data-bound-by-value="<?php echo $iso; ?>">
                    <div class="small-4 column">
                        <?php // TODO: handle translation for the labels nicer... somnehow ?>
                        <label for="address-region-<?php echo $iso; ?>"><?php echo t(Sao_Yves_Library_L::REGION . '_' . $iso); ?>:
                            *</label>
                    </div>
                    <div class="small-8 column">
                        <select class="input-field" name="region" id="address-region-<?php echo $iso; ?>" required data-error-label="<?php echo t(Sao_Yves_Library_L::REGION_ERROR); ?>" disabled>
                            <option value="" selected>-----
                                <?php foreach ($regionsArray as $regionShort => $regionLong): ?>
                            <option value="<?php echo $regionShort; ?>" <?php echo Sao_Yves_Library_Form_Html::getSelectedIf($form->region, $regionShort); ?>><?php echo $regionLong; ?>
                                <?php endforeach; ?>
                        </select>
                    </div>
                    <?php endforeach; ?>

                <li class="row">
                    <div class="small-4 column">
                        <label for="address-postal"><?php echo t(Sao_Yves_Library_L::POSTAL); ?>: *</label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="zip_code" id="address-postal" required <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->zip_code) ?> >
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('zip_code'), 'zip_code') ?>
                    </div>
                <li class="row hidden" data-bound-by="artwork_availability">
                    <div class="small-4 column">
                        <label for="pickup-date"><?php echo t(Sao_Yves_Library_L::PICKUP_DATE); ?>: *</label>
                    </div>
                    <div class="small-8 column">
                        <input class="input-field" type="text" name="pickup_date" id="pickup-date" required disabled <?php echo Sao_Yves_Library_Form_Html::getValueAttr($form->pickup_date) ?> data-datepicker>
                        <p style="color:green"><?php echo t(Sao_Yves_Library_L::PICKUP_DATE_INFO); ?></p>
                        <?php // TODO: fix the error field ?>
                        <?php echo Sao_Yves_Library_Form_Html::getErrorLabelIf($form->getErrors('pickup_date'), 'pickup_date') ?>
                    </div>
                <li class="row hidden" data-bound-by="artwork_availability">
                    <div class="small-4 column">
                        <label for="pickup-time"><?php echo t(Sao_Yves_Library_L::PICKUP_READY_TIME); ?>: *</label>
                    </div>
                    <div class="small-4 column">
                        <select class="input-field" name="pickup_ready_time" id="pickup-time" required disabled>
                            <option value="" selected>-----
                                <?php foreach ($readyTimes as $timeShort => $timeLong): ?>
                            <option value="<?php echo $timeShort; ?>" <?php echo Sao_Yves_Library_Form_Html::getSelectedIf($timeShort, $form->pickup_ready_time); ?>><?php echo $timeLong; ?>
                                <?php endforeach; ?>
                        </select>
                        <?php // TODO: fix the error field ?>
                    </div>
                    <div class="small-4 column">
                        <select class="input-field" name="pickup_close_time" id="pickup-time2" required disabled>
                            <option value="" selected>-----
                                <?php foreach ($closeTimes as $timeShort => $timeLong): ?>
                            <option value="<?php echo $timeShort; ?>" <?php echo Sao_Yves_Library_Form_Html::getSelectedIf($timeShort, $form->pickup_close_time); ?>><?php echo $timeLong; ?>
                                <?php endforeach; ?>
                        </select>
                        <?php // TODO: fix the error field ?>
                    </div>
                <li class="row form-action">
                    <div class="large-offset-4 large-8 column">
                        <input type="submit" value="<?php echo t(Sao_Yves_Library_L::SUBMIT); ?>" class="submit-button">
                    </div>
            </ul>
        </form>
        <?php
        $cActiveForm = $this->beginWidget('CActiveForm', array('htmlOptions' => array('class' => 'styled-form artwork-availability-form'), 'action' => $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_ARTIST_ARTWORK_AVAILABILITY))); ?>
        <?php $this->endWidget(); ?>
    </section>
</div>
