<?php $entity = $this->data; ?>

<div style="font-size: 16px;">
    <?php echo $entity->getBaseCurrency()->getIsoCode(); ?>
    <?php echo __('to'); ?>
    <?php echo $entity->getTargetCurrency()->getIsoCode(); ?>
</div>

<br />
<br />

<div>
    <?php echo __('Last update'); ?>: <?php echo ProjectA_Shared_Library_Date::dateTime($entity->getUpdatedAt()); ?>
</div>

<br />
<br />
<br />

<?php echo $this->form; ?>