<?php echo $this->doctype('XHTML5'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta charset="utf-8">
    <title>Zed v2 (<?php echo APPLICATION_ENV ?>)</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->partial('Partials2/include.phtml', array()); ?>
</head>
<body>
    <script type="text/javascript">
        <?php $request = Zend_Controller_Front::getInstance()->getRequest(); ?>
        zed.vars.exchange.page.current.module = '<?php echo $request->getParam('module'); ?>';
        zed.vars.exchange.page.current.controller = '<?php echo $request->getParam('controller'); ?>';
        zed.vars.exchange.page.current.action = '<?php echo $request->getParam('action'); ?>';
    </script>

    <?php echo $this->partial('Partials2/header.phtml', array('currentController' => $this->currentController)); ?>
    <?php echo $this->partial('Partials2/tabs.phtml', array()); ?>

    <main class="zed:main" role="main" id="main">
        <header class="zed:main__header clearfix">
            <h1><?= $this->navigation()->setRenderInvisible(true)->getCurrentPageTitle(); ?></h1>
            <?php
            echo $this->navigation()->breadcrumbs()
                ->setPartial('Partials2/breadcrumbs.phtml')
                ->setRenderInvisible(true)
                ->setLinkLast(true)
                ->setMinDepth(0)
                ->render();
            ?>
        </header>

        <?php echo $this->partial('Partials2/messages.phtml', array()); ?>

        <?php echo $this->partial('Partials2/manual.phtml', array()); ?>




        <?php echo $this->layout()->content; ?>

    </main>
</body>
