#!/bin/bash

SETUP='spryker'
DATABASE_ENGINE='MySQL'
DATABASE_NAME='DE_development_zed'
DATABASE_USER='development'
DATABASE_PASSWORD='mate20mg'
REDIS_PORT='10009'
ELASTIC_SEARCH_PORT='10005'
ELASTIC_SEARCH_INDEX='de_search'
VERBOSITY='-v'
CONSOLE=vendor/bin/console
