#!/bin/bash

SETUP='spryker'
DATABASE_DEFAULT_ENGINE='postgresql'
DATABASE_NAME='DE_development_zed'
DATABASE_USER='development'
DATABASE_PASSWORD='mate20mg'
REDIS_PORT='10009'
ELASTIC_SEARCH_PORT='10005'
ELASTIC_SEARCH_INDEX='de_search'
VERBOSITY='-v'
CONSOLE=vendor/bin/console
RABBITMQ_HOST=localhost
RABBITMQ_WEB_PORT=15672
RABBITMQ_USER=admin
RABBITMQ_PASS=mate20mg
RABBITMQ_VHOST=DE_development_zed
