<div class="checkout-progress" id="checkout-progressbar">
    <h2><?php echo t( Sao_Yves_Library_L::SECURE_SHOPPING ); ?></h2>
    <ol class="horizontal-list">
      <li class="visible disabled step-shipping-address step-billing-address"><b class="label"><?php echo t( Sao_Yves_Library_L::ADDRESS ); ?></b>
      <li class="visible disabled step-payment"><b class="label"><?php echo t( Sao_Yves_Library_L::PAYMENT ); ?></b>
      <li class="visible disabled step-review"><b class="label"><?php echo t( Sao_Yves_Library_L::CHECKOUT_REVIEW ); ?></b>
    </ol>
</div>
