<footer class="page-footer">
  <div class="row">
    <h1 class="large-3 small-3 column"><?php echo t(Sao_Yves_Library_L::COPYRIGHT); ?></h1>
    <nav class="large-9 small-9 column">
      <ul class="unstyled horizontal-list text-right">
        <li><a href="http://www.saatchionline.com/privacy" target="_blank">Privacy Policy</a>
        <li><a href="http://www.saatchionline.com/copyright" target="_blank">Copyright Policy</a>
        <li><a href="http://www.saatchionline.com/terms" target="_blank">Terms and Conditions</a>
      </ul>
    </nav>
  </div>
</footer>

<?php $this->renderPartial('layouts/partials/scripts', array()); ?>
