<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $this->pageTitle ?> - saatchi checkout</title>
    <?php $this->renderPartial('layouts/partials/styles', array()); ?>
    <?php if (isset($_SERVER['HTTP_USER_AGENT']) && preg_match('/(?i)msie [1-8]/', $_SERVER['HTTP_USER_AGENT'])): ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <script src="<?php echo Sao_Yves_Library_Routing_UrlManager::createScriptUrl('vendor/html5shiv.js'); ?>"></script>
    <?php endif; ?>
    <script src="//cdn.optimizely.com/js/12533397.js" defer></script>
