<?php

namespace Pyz\Zed\Customer\Component\Model;

use ProjectA\Zed\Customer\Component\Model\OrderItemStatusMapping as CoreOrderItemStatusMapping;
use Pyz\Zed\Sales\Component\ConstantsInterface\Orderprocess as StatusConstants;

class OrderItemStatusMapping extends CoreOrderItemStatusMapping
{
    const CUSTOMER_ORDER_STATUS_RECEIVED = 'customer.order.status.received';
    const CUSTOMER_ORDER_STATUS_IN_PROGRESS = 'customer.order.status.in.progress';
    const CUSTOMER_ORDER_STATUS_SHIPPED = 'customer.order.status.shipped';
    const CUSTOMER_ORDER_STATUS_COMPLETED = 'customer.order.status.completed';
    const CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS = 'customer.order.status.return.in.progress';
    const CUSTOMER_ORDER_STATUS_CANCELED = 'customer.order.status.mapping.canceled';


    protected $statusMapping = [
        StatusConstants::STATE_NEW => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_INIT_PAYMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_WAITING_FOR_AUTHORIZATION_APPOINTMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_WAITING_FOR_PREAUTHORIZATION_APPOINTMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_CLARIFY_WAITING_FOR_PREAUTHORIZATION_APPOINTMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_CLARIFY_WAITING_FOR_AUTHORIZATION_APPOINTMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_CLARIFY_WAITING_FOR_PAID => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_PAYMENT_AUTHORIZED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_WAITING_FOR_RECEIPT_OF_PAYMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_PAYMENT_NOT_REDIRECTED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_CLARIFY_PAYMENT_REMINDED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_UNDERPAID => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_CLARIFY_UNDERPAID => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_CLARIFY_WAITING_FOR_CAPTURE_APPOINTMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_WAITING_FOR_AUTHORIZATION_APPOINTMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_CLARIFY_WAITING_FOR_CAPTURE_APPOINTMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_CLARIFY_CAPTURE_FAILED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_PAYMENT_AUTHORIZED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_INVALID => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_READY_FOR_INVOICE => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_INVOICE_CREATED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_WAITING_FOR_PAYMENT => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_PAID => self::CUSTOMER_ORDER_STATUS_RECEIVED,
//        StatusConstants::STATE_PAYMENT_REMINDED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_PAYMENT_REDIRECTED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_PAYMENT_NOT_REDIRECTED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_PAYMENT_PREAUTHORIZED => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_INIT_CAPTURE_PROCESS => self::CUSTOMER_ORDER_STATUS_RECEIVED,
        StatusConstants::STATE_PAYONE_CAPTURED => self::CUSTOMER_ORDER_STATUS_RECEIVED,

//        StatusConstants::STATE_FULFILLMENT_PROCESS_INITIALIZED => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_READY_FOR_EXPORT => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_EXPORTED => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_EXPORT_CONFIRMED => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_CLARIFY_DELIVERY_FAILED => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_CLARIFY_EK_DELIVERY_FAILED => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_CLARIFY_OWN_DELIVERY_FAILED => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_CANCELLATION_PROCESS_INITIALIZED => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_CLARIFY_REACTIVATE_VOUCHER_CODE => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,
//        StatusConstants::STATE_CLARIFY_REFUND_MONEY => self::CUSTOMER_ORDER_STATUS_IN_PROGRESS,

//        StatusConstants::STATE_SHIPPED => self::CUSTOMER_ORDER_STATUS_SHIPPED,
//        StatusConstants::STATE_FULFILLED => self::CUSTOMER_ORDER_STATUS_COMPLETED,

        StatusConstants::STATE_EXPORTABLE => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,
//        StatusConstants::STATE_DUNNING_PROCESS_INITIALIZED => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,
//        StatusConstants::STATE_CLARIFY_DUNNING => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,
//        StatusConstants::STATE_RETURN_DEBIT_NOTE_PROCESS_INITIALIZED => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,
//        StatusConstants::STATE_CLARIFY_RETURN_DEBIT_NOTE => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,

//        StatusConstants::STATE_COMPLETED_BUT_REVERSIBLE => self::CUSTOMER_ORDER_STATUS_COMPLETED,
//        StatusConstants::STATE_COMPLETED => self::CUSTOMER_ORDER_STATUS_COMPLETED,
        StatusConstants::STATE_CLOSED => self::CUSTOMER_ORDER_STATUS_COMPLETED,

//        StatusConstants::STATE_RETURN_PROCESS_INITIALIZED => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,

//        StatusConstants::STATE_RETURN_ARRIVED => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,
//        StatusConstants::STATE_RETURN_ACCEPTED => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,
//        StatusConstants::STATE_RETURN_DECLINED => self::CUSTOMER_ORDER_STATUS_RETURN_IN_PROGRESS,

//        StatusConstants::STATE_CLARIFY_REVERSE_ORDER_CREATED => self::CUSTOMER_ORDER_STATUS_CANCELED
    ];
    
}
