<?php if (!isset($_SERVER['HTTP_X_REQUESTED_WITH']) && APPLICATION_ENV != 'production' && ProjectA_Shared_Library_Config::get('yves')->browserConsole) : ?>
<script>
    if (window.console) {
        console.log("Execution Time: <?php echo $ms; ?> ms");
        console.log("Path: <?php echo ProjectA_Yves_Library_Yii::app()->controller->route; ?>");
        console.log("Views: <?php echo implode(', ',$this->views); ?>");
        <?php $stats = Sao_Yves_Application_Component_Model_Factory::getStorage()->getStats(); ?>
        console.log("Memcache: <?php echo $stats['count']['read']; ?> read, <?php echo $stats['count']['write']; ?> write, <?php echo $stats['count']['delete']; ?> delete");
        console.log("Memcache read keys: <?php echo implode(', ', $stats['keys']['read']); ?>");
        console.log("Memcache written keys: <?php echo implode(', ', $stats['keys']['write']); ?>");
        console.log("Memcache deleted keys: <?php echo implode(', ', $stats['keys']['delete']); ?>");
        console.log("Solr: <?php echo ProjectA_Shared_Library_Solr_HttpTransport::getRequestCount() ?> requests");
        console.log("Solr time for requests: <?php echo ProjectA_Shared_Library_Solr_HttpTransport::getRequestTime() ?>s");
        console.log("Yc_Base_Controller::renderPartial <?php echo ProjectA_Yves_Library_Base_Controller::$time ?>");


    }
</script>
<?php endif; ?>