<?php
/**
 * @var $this                IndexController
 * @var $registerRoute       string
 * @var $loginRoute          string
 * @var $loginForm           Customer_LoginForm
 * @var $registerForm        Customer_CreateAccountForm
 * @var $loginOrRegisterForm Customer_LoginOrRegisterForm
 */

/*
 * Facebook-url at legacy @ 2013-05-20
 * https://www.facebook.com/dialog/oauth
 * ?display=popup
 * &domain=www.saatchionline.com
 * &scope=email,publish_stream
 * &e2e={}
 * &app_id=112537152116651
 * &locale=en_US
 * &sdk=joey
 * &client_id=112537152116651
 * &redirect_uri=http://static.ak.facebook.com/connect/xd_arbiter.php?version=24#cb=f2c1199bc
 * &origin=http://www.saatchionline.com/f2917c93f
 * &domain=www.saatchionline.com
 * &relation=opener
 * &frame=f318c3eaa
 * &origin=1
 * &response_type=token,signed_request
 */

?>
<div class="row login-register-container">
  <form action="<?= $this->createAbsoluteUrl(Sao_Yves_Library_Routing_UrlManager::ROUTE_CUSTOMER_LOGINORREGISTER)?>" method="post" class="large-6 large-offset-1 column login-register-form styled-form" id="login-form" data-error-label="<?php echo t( Sao_Yves_Library_L::REQUIRED_FIELD_ERROR_LABEL ); ?>" novalidate data-js-validate>
    <?= ProjectA_Yves_Library_Yii::app()->getRequest()->getCsrfInputField() ?>
    <input type="hidden" value="<?php $returnUrl; ?>">

    <h1 class="heading text-center">
      <a href="<?php echo $facebookAuthURL; ?>" class="facebook-button large"><?php echo t(Sao_Yves_Library_L::LOGIN_WITH_FACEBOOK); ?></a>
    </h1>

    <hr data-separator="<?php echo t(Sao_Yves_Library_L::WORD_OR); ?>">

    <h1 class="heading main"><?php echo t(Sao_Yves_Library_L::SIGNIN); ?></h1>

    <section class="row email-container">
      <h2 class="heading column register hidden"><?php echo t(Sao_Yves_Library_L::LOGIN_HEADER_MAIL); ?></h2>
      <h2 class="heading column login"><?php echo t(Sao_Yves_Library_L::LOGIN_HEADER_MAIL_USERNAME); ?></h2>

      <dl class="column small-10">
        <dt>
          <label for="mail" class="register hidden"><?php echo t(Sao_Yves_Library_L::LOGIN_MAIL); ?></label>
          <label for="mail" class="login"><?php echo t(Sao_Yves_Library_L::LOGIN_MAIL_USERNAME); ?></label>
        <dd>
          <input name="Customer_LoginOrRegisterForm[email]" value="<?= CHtml::encode($loginOrRegisterForm->email) ?>" type="email" id="mail" class="input-field" required data-pattern="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}$" data-error-label="<?php echo t(Sao_Yves_Library_L::LOGIN_ERROR_MAIL); ?>" data-error-pattern-label="<?php echo t(Sao_Yves_Library_L::ERROR_LOGIN_PATTERN); ?>">
      </dl>
    </section>
    <section class="row">
      <h2 class="heading column"><?php echo t(Sao_Yves_Library_L::IS_PASSWORD_AVAILABLE); ?></h2>

      <dl class="column small-10 togglers-container">
        <dt class="toggler-container">
          <label class="toggler" for="input-context-register">
            <input name="Customer_LoginOrRegisterForm[context]" <?php if($loginOrRegisterForm->context == Sao_Yves_Customer_Component_Form_LoginOrRegister::CONTEXT_REGISTER): ?>checked="checked"<?php endif; ?> type="radio" class="offset-radio styled-radio" value="<?= Sao_Yves_Customer_Component_Form_LoginOrRegister::CONTEXT_REGISTER ?>" id="input-context-register">
            <?php echo t(Sao_Yves_Library_L::NO_PASSWORD_AVAILABLE); ?>
          </label>

        <dd class="hidden toggable">
          <dl>
              <h2 class="sub-heading"><?php echo t( Sao_Yves_Library_L::REQUIRED_FIELDS_INFO ); ?></h2>
            <dt>
              <label for="input-first-name"><?php echo t(Sao_Yves_Library_L::LOGIN_FIRST_NAME); ?> *</label>
            <dd>
              <input name="Customer_LoginOrRegisterForm[first_name]" value="<?= CHtml::encode($registerForm->first_name) ?>" type="text" class="input-field" name="new-user-first-name" id="input-first-name" required data-error-label="<?php echo t(Sao_Yves_Library_L::LOGIN_ERROR_FIRSTNAME); ?>">
            <dt>
              <label for="input-last-name"><?php echo t(Sao_Yves_Library_L::LOGIN_LAST_NAME); ?> *</label>
            <dd>
              <input name="Customer_LoginOrRegisterForm[last_name]" value="<?= CHtml::encode($registerForm->last_name) ?>" type="text" class="input-field" id="input-last-name" required data-error-label="<?php echo t(Sao_Yves_Library_L::LOGIN_ERROR_LASTNAME); ?>">
            <dt>
              <label for="input-password"><?php echo t(Sao_Yves_Library_L::LOGIN_PASSWORD); ?> *</label>
            <dd>
              <input name="Customer_LoginOrRegisterForm[password][<?= Sao_Yves_Customer_Component_Form_LoginOrRegister::CONTEXT_REGISTER ?>]" type="password" class="input-field" id="input-password" required pattern="[A-Za-z][0-9]|[0-9][A-Za-z]" data-min-length="6" data-error-label="<?php echo t(Sao_Yves_Library_L::LOGIN_ERROR_PASSWORD); ?>" data-error-pattern-label="<?php echo t(Sao_Yves_Library_L::ERROR_PASSWORD_PATTERN); ?>" data-error-min-length-label="<?php echo t(Sao_Yves_Library_L::ERROR_PASSWORD_LENGTH); ?>">
          </dl>

        <dd class="form-action action-register-container hidden toggable">
          <button type="submit" class="submit-button"><?php echo t(Sao_Yves_Library_L::REGISTER); ?>  ▶</button>

        <dt class="toggler-container">
          <label class="toggler" for="input-context-login">
            <input name="Customer_LoginOrRegisterForm[context]" <?php if($loginOrRegisterForm->context != Sao_Yves_Customer_Component_Form_LoginOrRegister::CONTEXT_REGISTER): ?>checked="checked"<?php endif; ?> type="radio" class="offset-radio styled-radio" value="<?= Sao_Yves_Customer_Component_Form_LoginOrRegister::CONTEXT_LOGIN ?>" id="input-context-login">
            <?php echo t(Sao_Yves_Library_L::YES_PASSWORD_AVAILABLE); ?>
          </label>
          <input name="Customer_LoginOrRegisterForm[fullname_asavt]" <?php /* This is fake captcha */ ?> type="text" class="hidden" value="<?= CHtml::encode($loginOrRegisterForm->fullname_asavt) ?>">

        <dd class="toggable">
          <input name="Customer_LoginOrRegisterForm[password][<?= Sao_Yves_Customer_Component_Form_LoginOrRegister::CONTEXT_LOGIN ?>]" type="password" class="input-field" id="input-password-login" required data-error-label="<?php echo t(Sao_Yves_Library_L::LOGIN_ERROR_PASSWORD); ?>">

        <dd class="toggable">
          <?php

          /**
           * by request from ticket #300, hardcoding the URL
           * https://project-a.codebasehq.com/projects/saatchi/tickets/300
           */

          /* <small><a href="<?php echo $this->createAbsoluteUrl($passwordRoute); ?>"><?= t(L::FORGOT_PASSWORD) ?></a></small> */

          ?>
          <small><a href="/accounts/reset-password?referrer=/cart/merge"><?= t(Sao_Yves_Library_L::FORGOT_PASSWORD) ?></a></small>

        <dd class="form-actionn action-login-container toggable">
          <button type="submit" class="submit-button"><?php echo t(Sao_Yves_Library_L::LOGIN); ?>  ▶</button>

      </dl>
    </section>
  </form>
</div>
<aside class="perks horizontal row">
  <h1 class="heading"><?php echo t( Sao_Yves_Library_L::WHY_JOIN_HEADING ); ?></h1>
  <ul class="perks-list horizontal-list">
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_JOIN_REASON_1 ); ?>
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_JOIN_REASON_2 ); ?>
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_JOIN_REASON_3 ); ?>
    <li class="perk"><?php echo t( Sao_Yves_Library_L::WHY_JOIN_REASON_4 ); ?>
  </ul>
</aside>

<?php

Sao_Yves_Library_Assets_Manager::getInstance()->addJsFile(
  'vendor/require',
  array(
    'data-main'       => Sao_Yves_Library_Routing_UrlManager::createScriptUrl( 'saatchi' ),
    'data-controller' => 'login'
  )
);
