<section class="clearfix">
    <div class="g-2 sign-in complete-registration">
        <div class="content" class="clearfix">
            <?php if ($isFbRegistration) : ?>
                <h2 class="sectionHd"><?php echo t(Sao_Yves_Library_L::COMPLETE_YOUR_REGISTRATION); ?></h2>
                <script>
                    $(document).ready(function() {
                        $('#Customer_CreateAccountForm_customer_tax_number').focus();
                    });
                </script>
            <?php else : ?>
                <h2 class="sectionHd"><?php echo t(Sao_Yves_Library_L::REGISTER); ?></h2>
            <?php endif; ?>
            <?php $createAccountForm->renderAsWidget(
                    array('id' => 'customer-create-form', 'action' => $this->createAbsoluteUrl($registerRoute), 'htmlOptions' => array(
                        'autocomplete' => 'off',
                        'class' => 'clearfix'
                    )),
                    t(Sao_Yves_Library_L::LOGIN)
                );
            ?>

            <a href="<?php echo  $this->createAbsoluteUrl($switchRoute); ?>" class="registerBackBtn gray btn"><?php echo t(Sao_Yves_Library_L::BACK); ?></a>

        </div>
    </div>
    <div class="g-1 last safe-shopping">
        <div class="content">
            <h2><?php echo t(Sao_Yves_Library_L::SECURE_SHOPPING); ?></h2>
            <p><?php echo t(Sao_Yves_Library_L::REGPAGE_TRUSTICONS_TXT); ?></p>
            <div class="moneyBack"><div>Garantimos a devolução do seu dinheiro</div></div>
            <a href="https://selo.siteblindado.com.br/verificar?url=http://www.natue.com.br/" target="_blank" class="blindadoIconFooter">
                <img src="https://s3-sa-east-1.amazonaws.com/selo.siteblindado.com/seals_aw/natue.com.br/siteblindado_pr.gif" style="border-style: none">
            </a>
        </div>
    </div>
</section>
<section class="clearfix">
    <div class="g-5">
        <div class="content uspMain">
            <ul class="clearfix">
                <li class="hotline">
                    <a href="#" title="4007-1668 (capitais)&lt;br /&gt; 0800-600-1668 (localidades)">4007-1668 (capitais)<br>0800-600-1668 (localidades)</a>
                </li>
                <li class="advice">
                    <a href="#" title="Consulte médicos, farmacêuticos e nutricionistas da NU3 para aconselhá-los na compra de produtos via chat ou por telefone.">Chat on-line com <br>nutricionistas</a>
                </li>
                <li class="shipping">
                    FRETE GRÁTIS <br> acima de R$150,00
                </li>
            </ul>
        </div>
    </div>
</section>
